/**
 * Script to generate modules.gen.ts with topologically sorted modules
 * This ensures proper initialization order based on module dependencies
 */

import { readdirSync, statSync, writeFileSync, existsSync, readFileSync } from "fs";
import { join, basename } from "path";

interface ModuleInfo {
	name: string;
	path: string;
	className: string;
	moduleName: string;
	dependencies: string[];
}

async function discoverModules(): Promise<ModuleInfo[]> {
	const modulesDir = join(import.meta.dir, "..", "src", "modules");
	const entries = readdirSync(modulesDir);
	const modules: ModuleInfo[] = [];

	for (const entry of entries) {
		const modulePath = join(modulesDir, entry);
		const indexFile = join(modulePath, "index.ts");

		if (statSync(modulePath).isDirectory() && existsSync(indexFile)) {
			try {
				const content = readFileSync(indexFile, "utf-8");

				// Extract module name
				const moduleNameMatch = content.match(/readonly\s+moduleName\s*=\s*["'`]([^"'`]+)["'`]/);
				const moduleName = moduleNameMatch ? moduleNameMatch[1] : entry;

				// Extract dependencies
				const dependenciesMatch = content.match(/readonly\s+dependencies\s*=\s*\[([^\]]*)\]/);
				const dependencies = dependenciesMatch
					? dependenciesMatch[1]
						.split(",")
						.map((d) => d.trim().replace(/["'`]/g, ""))
						.filter((d): d is string => Boolean(d))
					: [];

				// Extract class name
				const classMatch = content.match(/export\s+class\s+(\w+Module)/);
				const className = classMatch ? classMatch[1] : `${entry.charAt(0).toUpperCase() + entry.slice(1)}Module`;

				modules.push({
					name: entry,
					path: `modules/${entry}`,
					className,
					moduleName,
					dependencies,
				});

				console.log(`✓ Found module: ${className} (${moduleName}) - dependencies: [${dependencies.join(", ")}]`);
			} catch (error) {
				console.warn(`⚠️  Could not parse module: ${entry}`, error);
			}
		}
	}

	return modules;
}

function topologicalSort(modules: ModuleInfo[]): ModuleInfo[] {
	const moduleMap = new Map<string, ModuleInfo>();
	const inDegree = new Map<string, number>();
	const adjacencyList = new Map<string, string[]>();

	// Initialize
	for (const mod of modules) {
		moduleMap.set(mod.moduleName, mod);
		inDegree.set(mod.moduleName, 0);
		adjacencyList.set(mod.moduleName, []);
	}

	// Build graph
	for (const mod of modules) {
		for (const dep of mod.dependencies) {
			if (!moduleMap.has(dep)) {
				throw new Error(
					`Module '${mod.moduleName}' depends on '${dep}', but '${dep}' is not registered.\n` +
					`Available modules: ${Array.from(moduleMap.keys()).join(", ")}`,
				);
			}

			const neighbors = adjacencyList.get(dep);
			if (neighbors) {
				neighbors.push(mod.moduleName);
			}

			const currentDegree = inDegree.get(mod.moduleName);
			if (currentDegree !== undefined) {
				inDegree.set(mod.moduleName, currentDegree + 1);
			} else {
				inDegree.set(mod.moduleName, 1);
			}
		}
	}

	// Find roots
	const queue: string[] = [];
	for (const [name, degree] of inDegree.entries()) {
		if (degree === 0) queue.push(name);
	}

	const sorted: ModuleInfo[] = [];

	// Process queue
	while (queue.length > 0) {
		const currentName = queue.shift()!;
		const currentModule = moduleMap.get(currentName);
		if (currentModule) {
			sorted.push(currentModule);
		}

		const neighbors = adjacencyList.get(currentName);
		if (neighbors) {
			for (const neighbor of neighbors) {
				const neighborDegree = inDegree.get(neighbor);
				if (neighborDegree !== undefined) {
					inDegree.set(neighbor, neighborDegree - 1);
					if (neighborDegree - 1 === 0) {
						queue.push(neighbor);
					}
				}
			}
		}
	}

	// Check for cycles
	if (sorted.length !== modules.length) {
		const unresolved = Array.from(inDegree.entries())
			.filter(([_, degree]) => degree > 0)
			.map(([name]) => name);

		throw new Error(`Circular dependency detected involving modules: ${unresolved.join(", ")}`);
	}

	return sorted;
}

async function generateModulesFile(modules: ModuleInfo[]) {
	const outputPath = join(import.meta.dir, "..", "src", "modules.gen.ts");

	// Generate imports
	const imports = modules
		.map((mod) => `import { ${mod.className} } from "./${mod.path}";`)
		.join("\n");

	// Generate module array with proper typing
	const moduleList = modules.map((mod) => `\t${mod.className},`).join("\n");

	// Generate module name type union
	const moduleNames = modules.map((mod) => `"${mod.moduleName}"`).join(" | ");

	// Generate module map type
	const moduleMapEntries = modules.map((mod) => `\t${mod.moduleName}: typeof ${mod.className};`).join("\n");

	const moduleTupleTypes = modules.map((mod) => `typeof ${mod.className}`).join(",");

	const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-modules.ts
 * 
 * This file exports all modules in topological order based on their dependencies.
 * Changes to module dependencies will require regenerating this file.
 */

import type { PaideiaModuleConstructor } from "./shared/module-interface";
${imports}

/**
 * All modules sorted in topological order based on dependencies.
 * Modules with no dependencies come first, followed by dependent modules.
 */
export const allModules = [
${moduleList}
] as [${moduleTupleTypes}];

/**
 * Module initialization order (for logging/debugging):
 * ${modules.map((m) => m.moduleName).join(" → ")}
 */

/**
 * Type representing all valid module names
 */
export type ModuleName = ${moduleNames};

/**
 * Map of module names to module constructors
 */
export interface ModuleMap {
${moduleMapEntries}
}

/**
 * Get a module by name
 */
export function getModuleByName<T extends ModuleName>(name: T): ModuleMap[T] {
	const moduleMap: Record<string, PaideiaModuleConstructor> = {
${modules.map((mod) => `\t\t"${mod.moduleName}": ${mod.className},`).join("\n")}
	};
	return moduleMap[name] as ModuleMap[T];
}

// Re-export all modules for convenience
${modules.map((mod) => `export { ${mod.className} };`).join("\n")}
`;

	writeFileSync(outputPath, content, "utf-8");
	console.log(`\n✅ Generated modules.gen.ts with ${modules.length} modules`);
	console.log(`📦 Module order: ${modules.map((m) => m.moduleName).join(" → ")}\n`);
}

async function main() {
	console.log("🔍 Discovering modules...\n");

	try {
		// Discover all modules
		const modules = await discoverModules();

		if (modules.length === 0) {
			console.error("❌ No modules found");
			process.exit(1);
		}

		console.log(`\n📊 Found ${modules.length} modules\n`);

		// Sort topologically
		console.log("🔀 Sorting modules topologically...\n");
		const sortedModules = topologicalSort(modules);

		// Generate the file
		await generateModulesFile(sortedModules);

		console.log("✨ Module generation complete!");
	} catch (error) {
		console.error("❌ Error generating modules:", error);
		process.exit(1);
	}
}

main();
