services:
  postgres:
    image: postgres:18
    container_name: paideia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: paideia
      POSTGRES_PASSWORD: paideia_password
      POSTGRES_DB: paideia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paideia"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      paideia_net:
        ipv4_address: 172.28.0.3

  vaults3:
    image: eniz1806/vaults3:latest
    container_name: paideia_vaults3
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      VAULTS3_ACCESS_KEY: paideia_s3
      VAULTS3_SECRET_KEY: paideia_s3_secret
    volumes:
      - vaults3_data:/data
      - vaults3_metadata:/metadata
    networks:
      paideia_net:
        ipv4_address: 172.28.0.4

  # drizzle-gateway:
  #   image: ghcr.io/drizzle-team/gateway:latest
  #   container_name: drizzle-gateway
  #   restart: unless-stopped
  #   ports:
  #     - "4983:4983"
  #   environment:
  #     PORT: 4983
  #     STORE_PATH: ./app
  #     DATABASE_URL: postgresql://paideia:paideia_password@postgres:5432/paideia_db
  #   volumes:
  #     - drizzle-gateway:/app
  #   networks:
  #     paideia_net:
  #       ipv4_address: 172.28.0.5
  #   depends_on:
  #     - postgres

volumes:
  vaults3_data:
  vaults3_metadata:
  postgres_data:
  # drizzle-gateway:

networks:
  paideia_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
