/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-modules.ts
 * 
 * This file exports all modules in topological order based on their dependencies.
 * Changes to module dependencies will require regenerating this file.
 */

import { InfrastructureModule } from "./modules/infrastructure";
import { UserModule } from "./modules/user";
import { NoteModule } from "./modules/note";
import { GradingModule } from "./modules/grading";
import { CoursesModule } from "./modules/courses";
import { DriveModule } from "./modules/drive";
import { PagesModule } from "./modules/pages";
import { WhiteboardModule } from "./modules/whiteboard";
import { QuizModule } from "./modules/quiz";
import { AssignmentModule } from "./modules/assignment";
import { FilesModule } from "./modules/files";
import { DiscussionModule } from "./modules/discussion";
import { EnrolmentModule } from "./modules/enrolment";

/**
 * All modules sorted in topological order based on dependencies.
 * Modules with no dependencies come first, followed by dependent modules.
 */
export const allModules = [
	InfrastructureModule,
	UserModule,
	NoteModule,
	GradingModule,
	CoursesModule,
	DriveModule,
	PagesModule,
	WhiteboardModule,
	QuizModule,
	AssignmentModule,
	FilesModule,
	DiscussionModule,
	EnrolmentModule,
] as [typeof InfrastructureModule,typeof UserModule,typeof NoteModule,typeof GradingModule,typeof CoursesModule,typeof DriveModule,typeof PagesModule,typeof WhiteboardModule,typeof QuizModule,typeof AssignmentModule,typeof FilesModule,typeof DiscussionModule,typeof EnrolmentModule];

/**
 * Module initialization order (for logging/debugging):
 * infrastructure → user → note → grading → courses → drive → pages → whiteboard → quiz → assignment → files → discussion → enrolment
 */

/**
 * Type representing all valid module names
 */
export type ModuleName = "infrastructure" | "user" | "note" | "grading" | "courses" | "drive" | "pages" | "whiteboard" | "quiz" | "assignment" | "files" | "discussion" | "enrolment";

/**
 * Map of module names to module constructors
 */
export interface ModuleMap {
	infrastructure: typeof InfrastructureModule;
	user: typeof UserModule;
	note: typeof NoteModule;
	grading: typeof GradingModule;
	courses: typeof CoursesModule;
	drive: typeof DriveModule;
	pages: typeof PagesModule;
	whiteboard: typeof WhiteboardModule;
	quiz: typeof QuizModule;
	assignment: typeof AssignmentModule;
	files: typeof FilesModule;
	discussion: typeof DiscussionModule;
	enrolment: typeof EnrolmentModule;
}

/**
 * Get a module by name
 */
export function getModuleByName<T extends ModuleName>(name: T): ModuleMap[T] {
	const moduleMap = {
		"infrastructure": InfrastructureModule,
		"user": UserModule,
		"note": NoteModule,
		"grading": GradingModule,
		"courses": CoursesModule,
		"drive": DriveModule,
		"pages": PagesModule,
		"whiteboard": WhiteboardModule,
		"quiz": QuizModule,
		"assignment": AssignmentModule,
		"files": FilesModule,
		"discussion": DiscussionModule,
		"enrolment": EnrolmentModule,
	};
	return moduleMap[name] as ModuleMap[T];
}

// Re-export all modules for convenience
export { InfrastructureModule };
export { UserModule };
export { NoteModule };
export { GradingModule };
export { CoursesModule };
export { DriveModule };
export { PagesModule };
export { WhiteboardModule };
export { QuizModule };
export { AssignmentModule };
export { FilesModule };
export { DiscussionModule };
export { EnrolmentModule };
