/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-modules.ts
 * 
 * This file exports all modules in topological order based on their dependencies.
 * Changes to module dependencies will require regenerating this file.
 */

import type { PaideiaModuleConstructor } from "./shared/module-interface";
import { AssignmentModule } from "./modules/assignment";
import { UserModule } from "./modules/user";
import { InfrastructureModule } from "./modules/infrastructure";
import { NoteModule } from "./modules/note";
import { DriveModule } from "./modules/drive";
import { PagesModule } from "./modules/pages";
import { CoursesModule } from "./modules/courses";
import { DiscussionModule } from "./modules/discussion";
import { WhiteboardModule } from "./modules/whiteboard";
import { QuizModule } from "./modules/quiz";
import { GradebookModule } from "./modules/gradebook";
import { EnrolmentModule } from "./modules/enrolment";

/**
 * All modules sorted in topological order based on dependencies.
 * Modules with no dependencies come first, followed by dependent modules.
 */
export const allModules = [
	AssignmentModule,
	UserModule,
	InfrastructureModule,
	NoteModule,
	DriveModule,
	PagesModule,
	CoursesModule,
	DiscussionModule,
	WhiteboardModule,
	QuizModule,
	GradebookModule,
	EnrolmentModule,
] as [typeof AssignmentModule,typeof UserModule,typeof InfrastructureModule,typeof NoteModule,typeof DriveModule,typeof PagesModule,typeof CoursesModule,typeof DiscussionModule,typeof WhiteboardModule,typeof QuizModule,typeof GradebookModule,typeof EnrolmentModule];

/**
 * Module initialization order (for logging/debugging):
 * assignment → user → infrastructure → note → drive → pages → courses → discussion → whiteboard → quiz → gradebook → enrolment
 */

/**
 * Type representing all valid module names
 */
export type ModuleName = "assignment" | "user" | "infrastructure" | "note" | "drive" | "pages" | "courses" | "discussion" | "whiteboard" | "quiz" | "gradebook" | "enrolment";

/**
 * Map of module names to module constructors
 */
export interface ModuleMap {
	assignment: typeof AssignmentModule;
	user: typeof UserModule;
	infrastructure: typeof InfrastructureModule;
	note: typeof NoteModule;
	drive: typeof DriveModule;
	pages: typeof PagesModule;
	courses: typeof CoursesModule;
	discussion: typeof DiscussionModule;
	whiteboard: typeof WhiteboardModule;
	quiz: typeof QuizModule;
	gradebook: typeof GradebookModule;
	enrolment: typeof EnrolmentModule;
}

/**
 * Get a module by name
 */
export function getModuleByName<T extends ModuleName>(name: T): ModuleMap[T] {
	const moduleMap: Record<string, PaideiaModuleConstructor> = {
		"assignment": AssignmentModule,
		"user": UserModule,
		"infrastructure": InfrastructureModule,
		"note": NoteModule,
		"drive": DriveModule,
		"pages": PagesModule,
		"courses": CoursesModule,
		"discussion": DiscussionModule,
		"whiteboard": WhiteboardModule,
		"quiz": QuizModule,
		"gradebook": GradebookModule,
		"enrolment": EnrolmentModule,
	};
	return moduleMap[name] as ModuleMap[T];
}

// Re-export all modules for convenience
export { AssignmentModule };
export { UserModule };
export { InfrastructureModule };
export { NoteModule };
export { DriveModule };
export { PagesModule };
export { CoursesModule };
export { DiscussionModule };
export { WhiteboardModule };
export { QuizModule };
export { GradebookModule };
export { EnrolmentModule };
