/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    notes: Note;
    pages: Page;
    courses: Course;
    'course-sections': CourseSection;
    'course-activity-module-links': CourseActivityModuleLink;
    'course-grade-tables': CourseGradeTable;
    whiteboards: Whiteboard;
    files: File;
    discussions: Discussion;
    enrollments: Enrollment;
    groups: Group;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    courses: {
      gradeTable: 'course-grade-tables';
      enrollments: 'enrollments';
      groups: 'groups';
      sections: 'course-sections';
    };
    'course-sections': {
      activityModules: 'course-activity-module-links';
      childSections: 'course-sections';
    };
    groups: {
      enrollments: 'enrollments';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'course-sections': CourseSectionsSelect<false> | CourseSectionsSelect<true>;
    'course-activity-module-links': CourseActivityModuleLinksSelect<false> | CourseActivityModuleLinksSelect<true>;
    'course-grade-tables': CourseGradeTablesSelect<false> | CourseGradeTablesSelect<true>;
    whiteboards: WhiteboardsSelect<false> | WhiteboardsSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    discussions: DiscussionsSelect<false> | DiscussionsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'system-grade-table': SystemGradeTable;
    'registration-settings': RegistrationSetting;
    'maintenance-settings': MaintenanceSetting;
    'site-policies': SitePolicy;
    'appearance-settings': AppearanceSetting;
    'analytics-settings': AnalyticsSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'system-grade-table': SystemGradeTableSelect<false> | SystemGradeTableSelect<true>;
    'registration-settings': RegistrationSettingsSelect<false> | RegistrationSettingsSelect<true>;
    'maintenance-settings': MaintenanceSettingsSelect<false> | MaintenanceSettingsSelect<true>;
    'site-policies': SitePoliciesSelect<false> | SitePoliciesSelect<true>;
    'appearance-settings': AppearanceSettingsSelect<false> | AppearanceSettingsSelect<true>;
    'analytics-settings': AnalyticsSettingsSelect<false> | AnalyticsSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      sandboxReset: TaskSandboxReset;
      autoSubmitQuiz: TaskAutoSubmitQuiz;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role?: ('admin' | 'content-manager' | 'analytics-viewer' | 'instructor' | 'student') | null;
  bio?: string | null;
  theme: 'light' | 'dark';
  direction: 'ltr' | 'rtl';
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  createdBy: number | User;
  content: string;
  contentMedia?: (number | Media)[] | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  description?: string | null;
  descriptionMedia?: (number | Media)[] | null;
  createdBy: number | User;
  content?: string | null;
  contentMedia?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug: string;
  description: string;
  descriptionMedia?: (number | Media)[] | null;
  status: 'draft' | 'published' | 'archived';
  recurringSchedules?:
    | {
        daysOfWeek: {
          day: number;
          id?: string | null;
        }[];
        startTime: string;
        endTime: string;
        startDate?: string | null;
        endDate?: string | null;
        id?: string | null;
      }[]
    | null;
  specificDates?:
    | {
        date: string;
        startTime: string;
        endTime: string;
        id?: string | null;
      }[]
    | null;
  thumbnail?: (number | null) | Media;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  createdBy: number | User;
  gradeTable?: {
    docs?: (number | CourseGradeTable)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  enrollments?: {
    docs?: (number | Enrollment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  groups?: {
    docs?: (number | Group)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  sections?: {
    docs?: (number | CourseSection)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-grade-tables".
 */
export interface CourseGradeTable {
  id: number;
  course: number | Course;
  courseTitle?: string | null;
  gradeLetters?:
    | {
        letter: string;
        minimumPercentage: number;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  user: number | User;
  userEmail?: string | null;
  course: number | Course;
  courseSlug?: string | null;
  courseTitle?: string | null;
  role: 'student' | 'teacher' | 'ta' | 'manager';
  status: 'active' | 'inactive' | 'completed' | 'dropped';
  enrolledAt?: string | null;
  completedAt?: string | null;
  groups?: (number | Group)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  course: number | Course;
  parent?: (number | null) | Group;
  path: string;
  description?: string | null;
  color?: string | null;
  maxMembers?: number | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  enrollments?: {
    docs?: (number | Enrollment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-sections".
 */
export interface CourseSection {
  id: number;
  course: number | Course;
  courseName?: string | null;
  courseSlug?: string | null;
  title: string;
  description?: string | null;
  parentSection?: (number | null) | CourseSection;
  parentSectionTitle?: string | null;
  contentOrder: number;
  activityModules?: {
    docs?: (number | CourseActivityModuleLink)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  childSections?: {
    docs?: (number | CourseSection)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-activity-module-links".
 */
export interface CourseActivityModuleLink {
  id: number;
  course: number | Course;
  courseName?: string | null;
  courseSlug?: string | null;
  section: number | CourseSection;
  sectionTitle?: string | null;
  contentOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboards".
 */
export interface Whiteboard {
  id: number;
  title: string;
  description?: string | null;
  descriptionMedia?: (number | Media)[] | null;
  content?: string | null;
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: number;
  title: string;
  description?: string | null;
  descriptionMedia?: (number | Media)[] | null;
  media?: (number | Media)[] | null;
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussions".
 */
export interface Discussion {
  id: number;
  title: string;
  description?: string | null;
  instructions?: string | null;
  dueDate?: string | null;
  requireThread?: boolean | null;
  requireReplies?: boolean | null;
  minReplies?: number | null;
  minWordsPerPost?: number | null;
  allowAttachments?: boolean | null;
  allowUpvotes?: boolean | null;
  allowEditing?: boolean | null;
  allowDeletion?: boolean | null;
  moderationRequired?: boolean | null;
  anonymousPosting?: boolean | null;
  groupDiscussion?: boolean | null;
  maxGroupSize?: number | null;
  threadSorting?: ('recent' | 'upvoted' | 'active' | 'alphabetical') | null;
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'courses';
        value: number | Course;
      }
    | {
        relationTo: 'discussions';
        value: number | Discussion;
      };
  meta?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sandboxReset' | 'autoSubmitQuiz';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sandboxReset' | 'autoSubmitQuiz') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'course-sections';
        value: number | CourseSection;
      } | null)
    | ({
        relationTo: 'course-activity-module-links';
        value: number | CourseActivityModuleLink;
      } | null)
    | ({
        relationTo: 'course-grade-tables';
        value: number | CourseGradeTable;
      } | null)
    | ({
        relationTo: 'whiteboards';
        value: number | Whiteboard;
      } | null)
    | ({
        relationTo: 'files';
        value: number | File;
      } | null)
    | ({
        relationTo: 'discussions';
        value: number | Discussion;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  bio?: T;
  theme?: T;
  direction?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  createdBy?: T;
  content?: T;
  contentMedia?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  descriptionMedia?: T;
  createdBy?: T;
  content?: T;
  contentMedia?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  descriptionMedia?: T;
  status?: T;
  recurringSchedules?:
    | T
    | {
        daysOfWeek?:
          | T
          | {
              day?: T;
              id?: T;
            };
        startTime?: T;
        endTime?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  specificDates?:
    | T
    | {
        date?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  thumbnail?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  createdBy?: T;
  gradeTable?: T;
  enrollments?: T;
  groups?: T;
  sections?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-sections_select".
 */
export interface CourseSectionsSelect<T extends boolean = true> {
  course?: T;
  courseName?: T;
  courseSlug?: T;
  title?: T;
  description?: T;
  parentSection?: T;
  parentSectionTitle?: T;
  contentOrder?: T;
  activityModules?: T;
  childSections?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-activity-module-links_select".
 */
export interface CourseActivityModuleLinksSelect<T extends boolean = true> {
  course?: T;
  courseName?: T;
  courseSlug?: T;
  section?: T;
  sectionTitle?: T;
  contentOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-grade-tables_select".
 */
export interface CourseGradeTablesSelect<T extends boolean = true> {
  course?: T;
  courseTitle?: T;
  gradeLetters?:
    | T
    | {
        letter?: T;
        minimumPercentage?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboards_select".
 */
export interface WhiteboardsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  descriptionMedia?: T;
  content?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  descriptionMedia?: T;
  media?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussions_select".
 */
export interface DiscussionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  instructions?: T;
  dueDate?: T;
  requireThread?: T;
  requireReplies?: T;
  minReplies?: T;
  minWordsPerPost?: T;
  allowAttachments?: T;
  allowUpvotes?: T;
  allowEditing?: T;
  allowDeletion?: T;
  moderationRequired?: T;
  anonymousPosting?: T;
  groupDiscussion?: T;
  maxGroupSize?: T;
  threadSorting?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  user?: T;
  userEmail?: T;
  course?: T;
  courseSlug?: T;
  courseTitle?: T;
  role?: T;
  status?: T;
  enrolledAt?: T;
  completedAt?: T;
  groups?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  course?: T;
  parent?: T;
  path?: T;
  description?: T;
  color?: T;
  maxMembers?: T;
  metadata?: T;
  enrollments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-grade-table".
 */
export interface SystemGradeTable {
  id: number;
  gradeLetters?:
    | {
        letter: string;
        minimumPercentage: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Maximum nesting depth for course categories. Leave empty for unlimited depth.
   */
  maxCategoryDepth?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-settings".
 */
export interface RegistrationSetting {
  id: number;
  disableRegistration?: boolean | null;
  showRegistrationButton?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-settings".
 */
export interface MaintenanceSetting {
  id: number;
  /**
   * When enabled, only administrators can access the system. All other users will be blocked from logging in.
   */
  maintenanceMode?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-policies".
 */
export interface SitePolicy {
  id: number;
  /**
   * Maximum total storage allowed per user for media files. Leave empty for unlimited storage.
   */
  userMediaStorageTotal?: number | null;
  /**
   * Maximum file size allowed for uploads across the site. Leave empty for unlimited size.
   */
  siteUploadLimit?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance-settings".
 */
export interface AppearanceSetting {
  id: number;
  /**
   * Select the primary color theme for the application. This affects buttons, links, and other interactive elements.
   */
  color?:
    | (
        | 'blue'
        | 'pink'
        | 'indigo'
        | 'green'
        | 'orange'
        | 'gray'
        | 'grape'
        | 'cyan'
        | 'lime'
        | 'red'
        | 'violet'
        | 'teal'
        | 'yellow'
      )
    | null;
  /**
   * Select the default border radius for components. This affects buttons, cards, inputs, and other elements.
   */
  radius?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  /**
   * Add external CSS stylesheet URLs that will be loaded on all pages. Stylesheets are loaded in the order listed, allowing you to control CSS cascade precedence.
   */
  additionalCssStylesheets?:
    | {
        /**
         * Full URL to the CSS stylesheet (e.g., https://example.com/style.css). Must be a valid HTTP/HTTPS URL.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload the main logo image for light mode. This will be displayed when the site is in light mode.
   */
  logoLight?: (number | null) | Media;
  /**
   * Upload the main logo image for dark mode. This will be displayed when the site is in dark mode.
   */
  logoDark?: (number | null) | Media;
  /**
   * Upload a compact version of the logo for light mode. This is typically used in smaller spaces like navigation bars.
   */
  compactLogoLight?: (number | null) | Media;
  /**
   * Upload a compact version of the logo for dark mode. This is typically used in smaller spaces like navigation bars.
   */
  compactLogoDark?: (number | null) | Media;
  /**
   * Upload the favicon for light mode. This is the small icon displayed in browser tabs and bookmarks.
   */
  faviconLight?: (number | null) | Media;
  /**
   * Upload the favicon for dark mode. This is the small icon displayed in browser tabs and bookmarks.
   */
  faviconDark?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings".
 */
export interface AnalyticsSetting {
  id: number;
  /**
   * Add external JavaScript script tags that will be loaded on all pages. Scripts are loaded in the order listed. Only external scripts with src attribute are allowed for security.
   */
  additionalJsScripts?:
    | {
        /**
         * Full URL to the JavaScript file (e.g., https://cloud.umami.is/script.js). Must be a valid HTTP/HTTPS URL.
         */
        src: string;
        /**
         * When enabled, the script will be executed after the document has been parsed.
         */
        defer?: boolean | null;
        /**
         * When enabled, the script will be executed asynchronously as soon as it is available.
         */
        async?: boolean | null;
        /**
         * Data attribute for website ID (e.g., for Umami analytics). This will be added as data-website-id attribute.
         */
        dataWebsiteId?: string | null;
        /**
         * Data attribute for domain (e.g., for Plausible analytics). This will be added as data-domain attribute.
         */
        dataDomain?: string | null;
        /**
         * Data attribute for site ID (e.g., for Fathom analytics). This will be added as data-site attribute.
         */
        dataSite?: string | null;
        /**
         * Data attribute for measurement ID (e.g., for Google Analytics). This will be added as data-measurement-id attribute.
         */
        dataMeasurementId?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-grade-table_select".
 */
export interface SystemGradeTableSelect<T extends boolean = true> {
  gradeLetters?:
    | T
    | {
        letter?: T;
        minimumPercentage?: T;
        id?: T;
      };
  maxCategoryDepth?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-settings_select".
 */
export interface RegistrationSettingsSelect<T extends boolean = true> {
  disableRegistration?: T;
  showRegistrationButton?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-settings_select".
 */
export interface MaintenanceSettingsSelect<T extends boolean = true> {
  maintenanceMode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-policies_select".
 */
export interface SitePoliciesSelect<T extends boolean = true> {
  userMediaStorageTotal?: T;
  siteUploadLimit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance-settings_select".
 */
export interface AppearanceSettingsSelect<T extends boolean = true> {
  color?: T;
  radius?: T;
  additionalCssStylesheets?:
    | T
    | {
        url?: T;
        id?: T;
      };
  logoLight?: T;
  logoDark?: T;
  compactLogoLight?: T;
  compactLogoDark?: T;
  faviconLight?: T;
  faviconDark?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings_select".
 */
export interface AnalyticsSettingsSelect<T extends boolean = true> {
  additionalJsScripts?:
    | T
    | {
        src?: T;
        defer?: T;
        async?: T;
        dataWebsiteId?: T;
        dataDomain?: T;
        dataSite?: T;
        dataMeasurementId?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSandboxReset".
 */
export interface TaskSandboxReset {
  input?: unknown;
  output: {
    message: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskAutoSubmitQuiz".
 */
export interface TaskAutoSubmitQuiz {
  input: {
    submissionId: number;
  };
  output: {
    message: string;
    submissionId: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}