/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  boolean,
  numeric,
  type AnyPgColumn,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_role = pgEnum("enum_users_role", [
  "admin",
  "content-manager",
  "analytics-viewer",
  "instructor",
  "student",
]);
export const enum_users_theme = pgEnum("enum_users_theme", ["light", "dark"]);
export const enum_users_direction = pgEnum("enum_users_direction", [
  "ltr",
  "rtl",
]);
export const enum_courses_status = pgEnum("enum_courses_status", [
  "draft",
  "published",
  "archived",
]);
export const enum_discussions_thread_sorting = pgEnum(
  "enum_discussions_thread_sorting",
  ["recent", "upvoted", "active", "alphabetical"],
);
export const enum_enrollments_role = pgEnum("enum_enrollments_role", [
  "student",
  "teacher",
  "ta",
  "manager",
]);
export const enum_enrollments_status = pgEnum("enum_enrollments_status", [
  "active",
  "inactive",
  "completed",
  "dropped",
]);
export const enum_payload_jobs_log_task_slug = pgEnum(
  "enum_payload_jobs_log_task_slug",
  ["inline", "sandboxReset", "autoSubmitQuiz"],
);
export const enum_payload_jobs_log_state = pgEnum(
  "enum_payload_jobs_log_state",
  ["failed", "succeeded"],
);
export const enum_payload_jobs_task_slug = pgEnum(
  "enum_payload_jobs_task_slug",
  ["inline", "sandboxReset", "autoSubmitQuiz"],
);
export const enum_appearance_settings_color = pgEnum(
  "enum_appearance_settings_color",
  [
    "blue",
    "pink",
    "indigo",
    "green",
    "orange",
    "gray",
    "grape",
    "cyan",
    "lime",
    "red",
    "violet",
    "teal",
    "yellow",
  ],
);
export const enum_appearance_settings_radius = pgEnum(
  "enum_appearance_settings_radius",
  ["xs", "sm", "md", "lg", "xl"],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    firstName: varchar("first_name"),
    lastName: varchar("last_name"),
    role: enum_users_role("role").default("student"),
    bio: varchar("bio"),
    theme: enum_users_theme("theme").notNull().default("light"),
    direction: enum_users_direction("direction").notNull().default("ltr"),
    avatar: integer("avatar_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    enableAPIKey: boolean("enable_a_p_i_key"),
    apiKey: varchar("api_key"),
    apiKeyIndex: varchar("api_key_index"),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    _verified: boolean("_verified"),
    _verificationToken: varchar("_verificationtoken"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_avatar_idx").on(columns.avatar),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt"),
    caption: varchar("caption"),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_created_by_idx").on(columns.createdBy),
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("createdBy_idx").on(columns.createdBy),
  ],
);

export const notes = pgTable(
  "notes",
  {
    id: serial("id").primaryKey(),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    content: varchar("content").notNull(),
    isPublic: boolean("is_public").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("notes_created_by_idx").on(columns.createdBy),
    index("notes_updated_at_idx").on(columns.updatedAt),
    index("notes_created_at_idx").on(columns.createdAt),
  ],
);

export const notes_rels = pgTable(
  "notes_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("notes_rels_order_idx").on(columns.order),
    index("notes_rels_parent_idx").on(columns.parent),
    index("notes_rels_path_idx").on(columns.path),
    index("notes_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [notes.id],
      name: "notes_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "notes_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description"),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    content: varchar("content"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("pages_created_by_idx").on(columns.createdBy),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
    index("createdBy_1_idx").on(columns.createdBy),
  ],
);

export const pages_rels = pgTable(
  "pages_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("pages_rels_order_idx").on(columns.order),
    index("pages_rels_parent_idx").on(columns.parent),
    index("pages_rels_path_idx").on(columns.path),
    index("pages_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [pages.id],
      name: "pages_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "pages_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const courses_recurring_schedules_days_of_week = pgTable(
  "courses_recurring_schedules_days_of_week",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    day: numeric("day", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("courses_recurring_schedules_days_of_week_order_idx").on(
      columns._order,
    ),
    index("courses_recurring_schedules_days_of_week_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [courses_recurring_schedules.id],
      name: "courses_recurring_schedules_days_of_week_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const courses_recurring_schedules = pgTable(
  "courses_recurring_schedules",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    startTime: varchar("start_time").notNull(),
    endTime: varchar("end_time").notNull(),
    startDate: timestamp("start_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    endDate: timestamp("end_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("courses_recurring_schedules_order_idx").on(columns._order),
    index("courses_recurring_schedules_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [courses.id],
      name: "courses_recurring_schedules_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const courses_specific_dates = pgTable(
  "courses_specific_dates",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    date: timestamp("date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    startTime: varchar("start_time").notNull(),
    endTime: varchar("end_time").notNull(),
  },
  (columns) => [
    index("courses_specific_dates_order_idx").on(columns._order),
    index("courses_specific_dates_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [courses.id],
      name: "courses_specific_dates_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const courses_tags = pgTable(
  "courses_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    tag: varchar("tag"),
  },
  (columns) => [
    index("courses_tags_order_idx").on(columns._order),
    index("courses_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [courses.id],
      name: "courses_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const courses = pgTable(
  "courses",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    description: varchar("description").notNull(),
    status: enum_courses_status("status").notNull().default("draft"),
    thumbnail: integer("thumbnail_id").references(() => media.id, {
      onDelete: "set null",
    }),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("courses_slug_idx").on(columns.slug),
    index("courses_thumbnail_idx").on(columns.thumbnail),
    index("courses_created_by_idx").on(columns.createdBy),
    index("courses_updated_at_idx").on(columns.updatedAt),
    index("courses_created_at_idx").on(columns.createdAt),
  ],
);

export const courses_rels = pgTable(
  "courses_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("courses_rels_order_idx").on(columns.order),
    index("courses_rels_parent_idx").on(columns.parent),
    index("courses_rels_path_idx").on(columns.path),
    index("courses_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [courses.id],
      name: "courses_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "courses_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const course_sections = pgTable(
  "course_sections",
  {
    id: serial("id").primaryKey(),
    course: integer("course_id")
      .notNull()
      .references(() => courses.id, {
        onDelete: "set null",
      }),
    title: varchar("title").notNull(),
    description: varchar("description"),
    parentSection: integer("parent_section_id").references(
      (): AnyPgColumn => course_sections.id,
      {
        onDelete: "set null",
      },
    ),
    contentOrder: numeric("content_order", { mode: "number" })
      .notNull()
      .default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("course_sections_course_idx").on(columns.course),
    index("course_sections_parent_section_idx").on(columns.parentSection),
    index("course_sections_updated_at_idx").on(columns.updatedAt),
    index("course_sections_created_at_idx").on(columns.createdAt),
  ],
);

export const course_activity_module_links = pgTable(
  "course_activity_module_links",
  {
    id: serial("id").primaryKey(),
    course: integer("course_id")
      .notNull()
      .references(() => courses.id, {
        onDelete: "set null",
      }),
    section: integer("section_id")
      .notNull()
      .references(() => course_sections.id, {
        onDelete: "set null",
      }),
    contentOrder: numeric("content_order", { mode: "number" })
      .notNull()
      .default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("course_activity_module_links_course_idx").on(columns.course),
    index("course_activity_module_links_section_idx").on(columns.section),
    index("course_activity_module_links_updated_at_idx").on(columns.updatedAt),
    index("course_activity_module_links_created_at_idx").on(columns.createdAt),
  ],
);

export const course_grade_tables_grade_letters = pgTable(
  "course_grade_tables_grade_letters",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    letter: varchar("letter").notNull(),
    minimumPercentage: numeric("minimum_percentage", {
      mode: "number",
    }).notNull(),
  },
  (columns) => [
    index("course_grade_tables_grade_letters_order_idx").on(columns._order),
    index("course_grade_tables_grade_letters_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [course_grade_tables.id],
      name: "course_grade_tables_grade_letters_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const course_grade_tables = pgTable(
  "course_grade_tables",
  {
    id: serial("id").primaryKey(),
    course: integer("course_id")
      .notNull()
      .references(() => courses.id, {
        onDelete: "set null",
      }),
    isActive: boolean("is_active").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("course_grade_tables_course_idx").on(columns.course),
    index("course_grade_tables_updated_at_idx").on(columns.updatedAt),
    index("course_grade_tables_created_at_idx").on(columns.createdAt),
    uniqueIndex("course_idx").on(columns.course),
  ],
);

export const whiteboards = pgTable(
  "whiteboards",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description"),
    content: varchar("content"),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("whiteboards_created_by_idx").on(columns.createdBy),
    index("whiteboards_updated_at_idx").on(columns.updatedAt),
    index("whiteboards_created_at_idx").on(columns.createdAt),
    index("createdBy_2_idx").on(columns.createdBy),
  ],
);

export const whiteboards_rels = pgTable(
  "whiteboards_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("whiteboards_rels_order_idx").on(columns.order),
    index("whiteboards_rels_parent_idx").on(columns.parent),
    index("whiteboards_rels_path_idx").on(columns.path),
    index("whiteboards_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [whiteboards.id],
      name: "whiteboards_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "whiteboards_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const files = pgTable(
  "files",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description"),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("files_created_by_idx").on(columns.createdBy),
    index("files_updated_at_idx").on(columns.updatedAt),
    index("files_created_at_idx").on(columns.createdAt),
    index("createdBy_3_idx").on(columns.createdBy),
  ],
);

export const files_rels = pgTable(
  "files_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("files_rels_order_idx").on(columns.order),
    index("files_rels_parent_idx").on(columns.parent),
    index("files_rels_path_idx").on(columns.path),
    index("files_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [files.id],
      name: "files_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "files_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const discussions = pgTable(
  "discussions",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description"),
    instructions: varchar("instructions"),
    dueDate: timestamp("due_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    requireThread: boolean("require_thread").default(true),
    requireReplies: boolean("require_replies").default(true),
    minReplies: numeric("min_replies", { mode: "number" }).default(2),
    minWordsPerPost: numeric("min_words_per_post", { mode: "number" }).default(
      50,
    ),
    allowAttachments: boolean("allow_attachments").default(true),
    allowUpvotes: boolean("allow_upvotes").default(true),
    allowEditing: boolean("allow_editing").default(true),
    allowDeletion: boolean("allow_deletion").default(false),
    moderationRequired: boolean("moderation_required").default(false),
    anonymousPosting: boolean("anonymous_posting").default(false),
    groupDiscussion: boolean("group_discussion").default(false),
    maxGroupSize: numeric("max_group_size", { mode: "number" }),
    threadSorting:
      enum_discussions_thread_sorting("thread_sorting").default("recent"),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("discussions_created_by_idx").on(columns.createdBy),
    index("discussions_updated_at_idx").on(columns.updatedAt),
    index("discussions_created_at_idx").on(columns.createdAt),
    index("createdBy_4_idx").on(columns.createdBy),
    index("dueDate_idx").on(columns.dueDate),
    index("threadSorting_idx").on(columns.threadSorting),
  ],
);

export const enrollments = pgTable(
  "enrollments",
  {
    id: serial("id").primaryKey(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    course: integer("course_id")
      .notNull()
      .references(() => courses.id, {
        onDelete: "set null",
      }),
    role: enum_enrollments_role("role").notNull(),
    status: enum_enrollments_status("status").notNull().default("active"),
    enrolledAt: timestamp("enrolled_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("enrollments_user_idx").on(columns.user),
    index("enrollments_course_idx").on(columns.course),
    index("enrollments_updated_at_idx").on(columns.updatedAt),
    index("enrollments_created_at_idx").on(columns.createdAt),
    uniqueIndex("user_course_idx").on(columns.user, columns.course),
  ],
);

export const enrollments_rels = pgTable(
  "enrollments_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    groupsID: integer("groups_id"),
  },
  (columns) => [
    index("enrollments_rels_order_idx").on(columns.order),
    index("enrollments_rels_parent_idx").on(columns.parent),
    index("enrollments_rels_path_idx").on(columns.path),
    index("enrollments_rels_groups_id_idx").on(columns.groupsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [enrollments.id],
      name: "enrollments_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["groupsID"]],
      foreignColumns: [groups.id],
      name: "enrollments_rels_groups_fk",
    }).onDelete("cascade"),
  ],
);

export const groups = pgTable(
  "groups",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    course: integer("course_id")
      .notNull()
      .references(() => courses.id, {
        onDelete: "set null",
      }),
    parent: integer("parent_id").references((): AnyPgColumn => groups.id, {
      onDelete: "set null",
    }),
    path: varchar("path").notNull(),
    description: varchar("description"),
    color: varchar("color"),
    maxMembers: numeric("max_members", { mode: "number" }),
    metadata: jsonb("metadata"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("groups_course_idx").on(columns.course),
    index("groups_parent_idx").on(columns.parent),
    uniqueIndex("groups_path_idx").on(columns.path),
    index("groups_updated_at_idx").on(columns.updatedAt),
    index("groups_created_at_idx").on(columns.createdAt),
    uniqueIndex("course_path_idx").on(columns.course, columns.path),
  ],
);

export const search = pgTable(
  "search",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    priority: numeric("priority", { mode: "number" }),
    meta: varchar("meta"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("search_updated_at_idx").on(columns.updatedAt),
    index("search_created_at_idx").on(columns.createdAt),
  ],
);

export const search_rels = pgTable(
  "search_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    coursesID: integer("courses_id"),
    discussionsID: integer("discussions_id"),
  },
  (columns) => [
    index("search_rels_order_idx").on(columns.order),
    index("search_rels_parent_idx").on(columns.parent),
    index("search_rels_path_idx").on(columns.path),
    index("search_rels_users_id_idx").on(columns.usersID),
    index("search_rels_courses_id_idx").on(columns.coursesID),
    index("search_rels_discussions_id_idx").on(columns.discussionsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [search.id],
      name: "search_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "search_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["coursesID"]],
      foreignColumns: [courses.id],
      name: "search_rels_courses_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["discussionsID"]],
      foreignColumns: [discussions.id],
      name: "search_rels_discussions_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_jobs_log = pgTable(
  "payload_jobs_log",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    executedAt: timestamp("executed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug("task_slug").notNull(),
    taskID: varchar("task_i_d").notNull(),
    input: jsonb("input"),
    output: jsonb("output"),
    state: enum_payload_jobs_log_state("state").notNull(),
    error: jsonb("error"),
  },
  (columns) => [
    index("payload_jobs_log_order_idx").on(columns._order),
    index("payload_jobs_log_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [payload_jobs.id],
      name: "payload_jobs_log_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_jobs = pgTable(
  "payload_jobs",
  {
    id: serial("id").primaryKey(),
    input: jsonb("input"),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    totalTried: numeric("total_tried", { mode: "number" }).default(0),
    hasError: boolean("has_error").default(false),
    error: jsonb("error"),
    taskSlug: enum_payload_jobs_task_slug("task_slug"),
    queue: varchar("queue").default("default"),
    waitUntil: timestamp("wait_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    processing: boolean("processing").default(false),
    meta: jsonb("meta"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_jobs_completed_at_idx").on(columns.completedAt),
    index("payload_jobs_total_tried_idx").on(columns.totalTried),
    index("payload_jobs_has_error_idx").on(columns.hasError),
    index("payload_jobs_task_slug_idx").on(columns.taskSlug),
    index("payload_jobs_queue_idx").on(columns.queue),
    index("payload_jobs_wait_until_idx").on(columns.waitUntil),
    index("payload_jobs_processing_idx").on(columns.processing),
    index("payload_jobs_updated_at_idx").on(columns.updatedAt),
    index("payload_jobs_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    notesID: integer("notes_id"),
    pagesID: integer("pages_id"),
    coursesID: integer("courses_id"),
    "course-sectionsID": integer("course_sections_id"),
    "course-activity-module-linksID": integer(
      "course_activity_module_links_id",
    ),
    "course-grade-tablesID": integer("course_grade_tables_id"),
    whiteboardsID: integer("whiteboards_id"),
    filesID: integer("files_id"),
    discussionsID: integer("discussions_id"),
    enrollmentsID: integer("enrollments_id"),
    groupsID: integer("groups_id"),
    searchID: integer("search_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_notes_id_idx").on(columns.notesID),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_courses_id_idx").on(columns.coursesID),
    index("payload_locked_documents_rels_course_sections_id_idx").on(
      columns["course-sectionsID"],
    ),
    index("payload_locked_documents_rels_course_activity_module_lin_idx").on(
      columns["course-activity-module-linksID"],
    ),
    index("payload_locked_documents_rels_course_grade_tables_id_idx").on(
      columns["course-grade-tablesID"],
    ),
    index("payload_locked_documents_rels_whiteboards_id_idx").on(
      columns.whiteboardsID,
    ),
    index("payload_locked_documents_rels_files_id_idx").on(columns.filesID),
    index("payload_locked_documents_rels_discussions_id_idx").on(
      columns.discussionsID,
    ),
    index("payload_locked_documents_rels_enrollments_id_idx").on(
      columns.enrollmentsID,
    ),
    index("payload_locked_documents_rels_groups_id_idx").on(columns.groupsID),
    index("payload_locked_documents_rels_search_id_idx").on(columns.searchID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["notesID"]],
      foreignColumns: [notes.id],
      name: "payload_locked_documents_rels_notes_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["coursesID"]],
      foreignColumns: [courses.id],
      name: "payload_locked_documents_rels_courses_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["course-sectionsID"]],
      foreignColumns: [course_sections.id],
      name: "payload_locked_documents_rels_course_sections_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["course-activity-module-linksID"]],
      foreignColumns: [course_activity_module_links.id],
      name: "payload_locked_documents_rels_course_activity_module_link_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["course-grade-tablesID"]],
      foreignColumns: [course_grade_tables.id],
      name: "payload_locked_documents_rels_course_grade_tables_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["whiteboardsID"]],
      foreignColumns: [whiteboards.id],
      name: "payload_locked_documents_rels_whiteboards_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["filesID"]],
      foreignColumns: [files.id],
      name: "payload_locked_documents_rels_files_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["discussionsID"]],
      foreignColumns: [discussions.id],
      name: "payload_locked_documents_rels_discussions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["enrollmentsID"]],
      foreignColumns: [enrollments.id],
      name: "payload_locked_documents_rels_enrollments_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["groupsID"]],
      foreignColumns: [groups.id],
      name: "payload_locked_documents_rels_groups_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["searchID"]],
      foreignColumns: [search.id],
      name: "payload_locked_documents_rels_search_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const system_grade_table_grade_letters = pgTable(
  "system_grade_table_grade_letters",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    letter: varchar("letter").notNull(),
    minimumPercentage: numeric("minimum_percentage", {
      mode: "number",
    }).notNull(),
  },
  (columns) => [
    index("system_grade_table_grade_letters_order_idx").on(columns._order),
    index("system_grade_table_grade_letters_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [system_grade_table.id],
      name: "system_grade_table_grade_letters_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const system_grade_table = pgTable("system_grade_table", {
  id: serial("id").primaryKey(),
  maxCategoryDepth: numeric("max_category_depth", { mode: "number" }),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const registration_settings = pgTable("registration_settings", {
  id: serial("id").primaryKey(),
  disableRegistration: boolean("disable_registration").default(false),
  showRegistrationButton: boolean("show_registration_button").default(true),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const maintenance_settings = pgTable("maintenance_settings", {
  id: serial("id").primaryKey(),
  maintenanceMode: boolean("maintenance_mode").default(false),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const site_policies = pgTable("site_policies", {
  id: serial("id").primaryKey(),
  userMediaStorageTotal: numeric("user_media_storage_total", {
    mode: "number",
  }).default(10737418240),
  siteUploadLimit: numeric("site_upload_limit", { mode: "number" }).default(
    20971520,
  ),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const appearance_settings_additional_css_stylesheets = pgTable(
  "appearance_settings_additional_css_stylesheets",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("appearance_settings_additional_css_stylesheets_order_idx").on(
      columns._order,
    ),
    index("appearance_settings_additional_css_stylesheets_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [appearance_settings.id],
      name: "appearance_settings_additional_css_stylesheets_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const appearance_settings = pgTable(
  "appearance_settings",
  {
    id: serial("id").primaryKey(),
    color: enum_appearance_settings_color("color").default("blue"),
    radius: enum_appearance_settings_radius("radius").default("sm"),
    logoLight: integer("logo_light_id").references(() => media.id, {
      onDelete: "set null",
    }),
    logoDark: integer("logo_dark_id").references(() => media.id, {
      onDelete: "set null",
    }),
    compactLogoLight: integer("compact_logo_light_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    compactLogoDark: integer("compact_logo_dark_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    faviconLight: integer("favicon_light_id").references(() => media.id, {
      onDelete: "set null",
    }),
    faviconDark: integer("favicon_dark_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("appearance_settings_logo_light_idx").on(columns.logoLight),
    index("appearance_settings_logo_dark_idx").on(columns.logoDark),
    index("appearance_settings_compact_logo_light_idx").on(
      columns.compactLogoLight,
    ),
    index("appearance_settings_compact_logo_dark_idx").on(
      columns.compactLogoDark,
    ),
    index("appearance_settings_favicon_light_idx").on(columns.faviconLight),
    index("appearance_settings_favicon_dark_idx").on(columns.faviconDark),
  ],
);

export const analytics_settings_additional_js_scripts = pgTable(
  "analytics_settings_additional_js_scripts",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    src: varchar("src").notNull(),
    defer: boolean("defer").default(false),
    async: boolean("async").default(false),
    dataWebsiteId: varchar("data_website_id"),
    dataDomain: varchar("data_domain"),
    dataSite: varchar("data_site"),
    dataMeasurementId: varchar("data_measurement_id"),
  },
  (columns) => [
    index("analytics_settings_additional_js_scripts_order_idx").on(
      columns._order,
    ),
    index("analytics_settings_additional_js_scripts_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [analytics_settings.id],
      name: "analytics_settings_additional_js_scripts_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const analytics_settings = pgTable("analytics_settings", {
  id: serial("id").primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const payload_jobs_stats = pgTable("payload_jobs_stats", {
  id: serial("id").primaryKey(),
  stats: jsonb("stats"),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, ({ one }) => ({
  createdBy: one(users, {
    fields: [media.createdBy],
    references: [users.id],
    relationName: "createdBy",
  }),
}));
export const relations_notes_rels = relations(notes_rels, ({ one }) => ({
  parent: one(notes, {
    fields: [notes_rels.parent],
    references: [notes.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [notes_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
}));
export const relations_notes = relations(notes, ({ one, many }) => ({
  createdBy: one(users, {
    fields: [notes.createdBy],
    references: [users.id],
    relationName: "createdBy",
  }),
  _rels: many(notes_rels, {
    relationName: "_rels",
  }),
}));
export const relations_pages_rels = relations(pages_rels, ({ one }) => ({
  parent: one(pages, {
    fields: [pages_rels.parent],
    references: [pages.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [pages_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
}));
export const relations_pages = relations(pages, ({ one, many }) => ({
  createdBy: one(users, {
    fields: [pages.createdBy],
    references: [users.id],
    relationName: "createdBy",
  }),
  _rels: many(pages_rels, {
    relationName: "_rels",
  }),
}));
export const relations_courses_recurring_schedules_days_of_week = relations(
  courses_recurring_schedules_days_of_week,
  ({ one }) => ({
    _parentID: one(courses_recurring_schedules, {
      fields: [courses_recurring_schedules_days_of_week._parentID],
      references: [courses_recurring_schedules.id],
      relationName: "daysOfWeek",
    }),
  }),
);
export const relations_courses_recurring_schedules = relations(
  courses_recurring_schedules,
  ({ one, many }) => ({
    _parentID: one(courses, {
      fields: [courses_recurring_schedules._parentID],
      references: [courses.id],
      relationName: "recurringSchedules",
    }),
    daysOfWeek: many(courses_recurring_schedules_days_of_week, {
      relationName: "daysOfWeek",
    }),
  }),
);
export const relations_courses_specific_dates = relations(
  courses_specific_dates,
  ({ one }) => ({
    _parentID: one(courses, {
      fields: [courses_specific_dates._parentID],
      references: [courses.id],
      relationName: "specificDates",
    }),
  }),
);
export const relations_courses_tags = relations(courses_tags, ({ one }) => ({
  _parentID: one(courses, {
    fields: [courses_tags._parentID],
    references: [courses.id],
    relationName: "tags",
  }),
}));
export const relations_courses_rels = relations(courses_rels, ({ one }) => ({
  parent: one(courses, {
    fields: [courses_rels.parent],
    references: [courses.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [courses_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
}));
export const relations_courses = relations(courses, ({ one, many }) => ({
  recurringSchedules: many(courses_recurring_schedules, {
    relationName: "recurringSchedules",
  }),
  specificDates: many(courses_specific_dates, {
    relationName: "specificDates",
  }),
  thumbnail: one(media, {
    fields: [courses.thumbnail],
    references: [media.id],
    relationName: "thumbnail",
  }),
  tags: many(courses_tags, {
    relationName: "tags",
  }),
  createdBy: one(users, {
    fields: [courses.createdBy],
    references: [users.id],
    relationName: "createdBy",
  }),
  _rels: many(courses_rels, {
    relationName: "_rels",
  }),
}));
export const relations_course_sections = relations(
  course_sections,
  ({ one }) => ({
    course: one(courses, {
      fields: [course_sections.course],
      references: [courses.id],
      relationName: "course",
    }),
    parentSection: one(course_sections, {
      fields: [course_sections.parentSection],
      references: [course_sections.id],
      relationName: "parentSection",
    }),
  }),
);
export const relations_course_activity_module_links = relations(
  course_activity_module_links,
  ({ one }) => ({
    course: one(courses, {
      fields: [course_activity_module_links.course],
      references: [courses.id],
      relationName: "course",
    }),
    section: one(course_sections, {
      fields: [course_activity_module_links.section],
      references: [course_sections.id],
      relationName: "section",
    }),
  }),
);
export const relations_course_grade_tables_grade_letters = relations(
  course_grade_tables_grade_letters,
  ({ one }) => ({
    _parentID: one(course_grade_tables, {
      fields: [course_grade_tables_grade_letters._parentID],
      references: [course_grade_tables.id],
      relationName: "gradeLetters",
    }),
  }),
);
export const relations_course_grade_tables = relations(
  course_grade_tables,
  ({ one, many }) => ({
    course: one(courses, {
      fields: [course_grade_tables.course],
      references: [courses.id],
      relationName: "course",
    }),
    gradeLetters: many(course_grade_tables_grade_letters, {
      relationName: "gradeLetters",
    }),
  }),
);
export const relations_whiteboards_rels = relations(
  whiteboards_rels,
  ({ one }) => ({
    parent: one(whiteboards, {
      fields: [whiteboards_rels.parent],
      references: [whiteboards.id],
      relationName: "_rels",
    }),
    mediaID: one(media, {
      fields: [whiteboards_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations_whiteboards = relations(
  whiteboards,
  ({ one, many }) => ({
    createdBy: one(users, {
      fields: [whiteboards.createdBy],
      references: [users.id],
      relationName: "createdBy",
    }),
    _rels: many(whiteboards_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_files_rels = relations(files_rels, ({ one }) => ({
  parent: one(files, {
    fields: [files_rels.parent],
    references: [files.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [files_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
}));
export const relations_files = relations(files, ({ one, many }) => ({
  createdBy: one(users, {
    fields: [files.createdBy],
    references: [users.id],
    relationName: "createdBy",
  }),
  _rels: many(files_rels, {
    relationName: "_rels",
  }),
}));
export const relations_discussions = relations(discussions, ({ one }) => ({
  createdBy: one(users, {
    fields: [discussions.createdBy],
    references: [users.id],
    relationName: "createdBy",
  }),
}));
export const relations_enrollments_rels = relations(
  enrollments_rels,
  ({ one }) => ({
    parent: one(enrollments, {
      fields: [enrollments_rels.parent],
      references: [enrollments.id],
      relationName: "_rels",
    }),
    groupsID: one(groups, {
      fields: [enrollments_rels.groupsID],
      references: [groups.id],
      relationName: "groups",
    }),
  }),
);
export const relations_enrollments = relations(
  enrollments,
  ({ one, many }) => ({
    user: one(users, {
      fields: [enrollments.user],
      references: [users.id],
      relationName: "user",
    }),
    course: one(courses, {
      fields: [enrollments.course],
      references: [courses.id],
      relationName: "course",
    }),
    _rels: many(enrollments_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_groups = relations(groups, ({ one }) => ({
  course: one(courses, {
    fields: [groups.course],
    references: [courses.id],
    relationName: "course",
  }),
  parent: one(groups, {
    fields: [groups.parent],
    references: [groups.id],
    relationName: "parent",
  }),
}));
export const relations_search_rels = relations(search_rels, ({ one }) => ({
  parent: one(search, {
    fields: [search_rels.parent],
    references: [search.id],
    relationName: "_rels",
  }),
  usersID: one(users, {
    fields: [search_rels.usersID],
    references: [users.id],
    relationName: "users",
  }),
  coursesID: one(courses, {
    fields: [search_rels.coursesID],
    references: [courses.id],
    relationName: "courses",
  }),
  discussionsID: one(discussions, {
    fields: [search_rels.discussionsID],
    references: [discussions.id],
    relationName: "discussions",
  }),
}));
export const relations_search = relations(search, ({ many }) => ({
  _rels: many(search_rels, {
    relationName: "_rels",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_jobs_log = relations(
  payload_jobs_log,
  ({ one }) => ({
    _parentID: one(payload_jobs, {
      fields: [payload_jobs_log._parentID],
      references: [payload_jobs.id],
      relationName: "log",
    }),
  }),
);
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: "log",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    notesID: one(notes, {
      fields: [payload_locked_documents_rels.notesID],
      references: [notes.id],
      relationName: "notes",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    coursesID: one(courses, {
      fields: [payload_locked_documents_rels.coursesID],
      references: [courses.id],
      relationName: "courses",
    }),
    "course-sectionsID": one(course_sections, {
      fields: [payload_locked_documents_rels["course-sectionsID"]],
      references: [course_sections.id],
      relationName: "course-sections",
    }),
    "course-activity-module-linksID": one(course_activity_module_links, {
      fields: [payload_locked_documents_rels["course-activity-module-linksID"]],
      references: [course_activity_module_links.id],
      relationName: "course-activity-module-links",
    }),
    "course-grade-tablesID": one(course_grade_tables, {
      fields: [payload_locked_documents_rels["course-grade-tablesID"]],
      references: [course_grade_tables.id],
      relationName: "course-grade-tables",
    }),
    whiteboardsID: one(whiteboards, {
      fields: [payload_locked_documents_rels.whiteboardsID],
      references: [whiteboards.id],
      relationName: "whiteboards",
    }),
    filesID: one(files, {
      fields: [payload_locked_documents_rels.filesID],
      references: [files.id],
      relationName: "files",
    }),
    discussionsID: one(discussions, {
      fields: [payload_locked_documents_rels.discussionsID],
      references: [discussions.id],
      relationName: "discussions",
    }),
    enrollmentsID: one(enrollments, {
      fields: [payload_locked_documents_rels.enrollmentsID],
      references: [enrollments.id],
      relationName: "enrollments",
    }),
    groupsID: one(groups, {
      fields: [payload_locked_documents_rels.groupsID],
      references: [groups.id],
      relationName: "groups",
    }),
    searchID: one(search, {
      fields: [payload_locked_documents_rels.searchID],
      references: [search.id],
      relationName: "search",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_system_grade_table_grade_letters = relations(
  system_grade_table_grade_letters,
  ({ one }) => ({
    _parentID: one(system_grade_table, {
      fields: [system_grade_table_grade_letters._parentID],
      references: [system_grade_table.id],
      relationName: "gradeLetters",
    }),
  }),
);
export const relations_system_grade_table = relations(
  system_grade_table,
  ({ many }) => ({
    gradeLetters: many(system_grade_table_grade_letters, {
      relationName: "gradeLetters",
    }),
  }),
);
export const relations_registration_settings = relations(
  registration_settings,
  () => ({}),
);
export const relations_maintenance_settings = relations(
  maintenance_settings,
  () => ({}),
);
export const relations_site_policies = relations(site_policies, () => ({}));
export const relations_appearance_settings_additional_css_stylesheets =
  relations(appearance_settings_additional_css_stylesheets, ({ one }) => ({
    _parentID: one(appearance_settings, {
      fields: [appearance_settings_additional_css_stylesheets._parentID],
      references: [appearance_settings.id],
      relationName: "additionalCssStylesheets",
    }),
  }));
export const relations_appearance_settings = relations(
  appearance_settings,
  ({ one, many }) => ({
    additionalCssStylesheets: many(
      appearance_settings_additional_css_stylesheets,
      {
        relationName: "additionalCssStylesheets",
      },
    ),
    logoLight: one(media, {
      fields: [appearance_settings.logoLight],
      references: [media.id],
      relationName: "logoLight",
    }),
    logoDark: one(media, {
      fields: [appearance_settings.logoDark],
      references: [media.id],
      relationName: "logoDark",
    }),
    compactLogoLight: one(media, {
      fields: [appearance_settings.compactLogoLight],
      references: [media.id],
      relationName: "compactLogoLight",
    }),
    compactLogoDark: one(media, {
      fields: [appearance_settings.compactLogoDark],
      references: [media.id],
      relationName: "compactLogoDark",
    }),
    faviconLight: one(media, {
      fields: [appearance_settings.faviconLight],
      references: [media.id],
      relationName: "faviconLight",
    }),
    faviconDark: one(media, {
      fields: [appearance_settings.faviconDark],
      references: [media.id],
      relationName: "faviconDark",
    }),
  }),
);
export const relations_analytics_settings_additional_js_scripts = relations(
  analytics_settings_additional_js_scripts,
  ({ one }) => ({
    _parentID: one(analytics_settings, {
      fields: [analytics_settings_additional_js_scripts._parentID],
      references: [analytics_settings.id],
      relationName: "additionalJsScripts",
    }),
  }),
);
export const relations_analytics_settings = relations(
  analytics_settings,
  ({ many }) => ({
    additionalJsScripts: many(analytics_settings_additional_js_scripts, {
      relationName: "additionalJsScripts",
    }),
  }),
);
export const relations_payload_jobs_stats = relations(
  payload_jobs_stats,
  () => ({}),
);

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role;
  enum_users_theme: typeof enum_users_theme;
  enum_users_direction: typeof enum_users_direction;
  enum_courses_status: typeof enum_courses_status;
  enum_discussions_thread_sorting: typeof enum_discussions_thread_sorting;
  enum_enrollments_role: typeof enum_enrollments_role;
  enum_enrollments_status: typeof enum_enrollments_status;
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug;
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state;
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug;
  enum_appearance_settings_color: typeof enum_appearance_settings_color;
  enum_appearance_settings_radius: typeof enum_appearance_settings_radius;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  notes: typeof notes;
  notes_rels: typeof notes_rels;
  pages: typeof pages;
  pages_rels: typeof pages_rels;
  courses_recurring_schedules_days_of_week: typeof courses_recurring_schedules_days_of_week;
  courses_recurring_schedules: typeof courses_recurring_schedules;
  courses_specific_dates: typeof courses_specific_dates;
  courses_tags: typeof courses_tags;
  courses: typeof courses;
  courses_rels: typeof courses_rels;
  course_sections: typeof course_sections;
  course_activity_module_links: typeof course_activity_module_links;
  course_grade_tables_grade_letters: typeof course_grade_tables_grade_letters;
  course_grade_tables: typeof course_grade_tables;
  whiteboards: typeof whiteboards;
  whiteboards_rels: typeof whiteboards_rels;
  files: typeof files;
  files_rels: typeof files_rels;
  discussions: typeof discussions;
  enrollments: typeof enrollments;
  enrollments_rels: typeof enrollments_rels;
  groups: typeof groups;
  search: typeof search;
  search_rels: typeof search_rels;
  payload_kv: typeof payload_kv;
  payload_jobs_log: typeof payload_jobs_log;
  payload_jobs: typeof payload_jobs;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  system_grade_table_grade_letters: typeof system_grade_table_grade_letters;
  system_grade_table: typeof system_grade_table;
  registration_settings: typeof registration_settings;
  maintenance_settings: typeof maintenance_settings;
  site_policies: typeof site_policies;
  appearance_settings_additional_css_stylesheets: typeof appearance_settings_additional_css_stylesheets;
  appearance_settings: typeof appearance_settings;
  analytics_settings_additional_js_scripts: typeof analytics_settings_additional_js_scripts;
  analytics_settings: typeof analytics_settings;
  payload_jobs_stats: typeof payload_jobs_stats;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_notes_rels: typeof relations_notes_rels;
  relations_notes: typeof relations_notes;
  relations_pages_rels: typeof relations_pages_rels;
  relations_pages: typeof relations_pages;
  relations_courses_recurring_schedules_days_of_week: typeof relations_courses_recurring_schedules_days_of_week;
  relations_courses_recurring_schedules: typeof relations_courses_recurring_schedules;
  relations_courses_specific_dates: typeof relations_courses_specific_dates;
  relations_courses_tags: typeof relations_courses_tags;
  relations_courses_rels: typeof relations_courses_rels;
  relations_courses: typeof relations_courses;
  relations_course_sections: typeof relations_course_sections;
  relations_course_activity_module_links: typeof relations_course_activity_module_links;
  relations_course_grade_tables_grade_letters: typeof relations_course_grade_tables_grade_letters;
  relations_course_grade_tables: typeof relations_course_grade_tables;
  relations_whiteboards_rels: typeof relations_whiteboards_rels;
  relations_whiteboards: typeof relations_whiteboards;
  relations_files_rels: typeof relations_files_rels;
  relations_files: typeof relations_files;
  relations_discussions: typeof relations_discussions;
  relations_enrollments_rels: typeof relations_enrollments_rels;
  relations_enrollments: typeof relations_enrollments;
  relations_groups: typeof relations_groups;
  relations_search_rels: typeof relations_search_rels;
  relations_search: typeof relations_search;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_jobs_log: typeof relations_payload_jobs_log;
  relations_payload_jobs: typeof relations_payload_jobs;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_system_grade_table_grade_letters: typeof relations_system_grade_table_grade_letters;
  relations_system_grade_table: typeof relations_system_grade_table;
  relations_registration_settings: typeof relations_registration_settings;
  relations_maintenance_settings: typeof relations_maintenance_settings;
  relations_site_policies: typeof relations_site_policies;
  relations_appearance_settings_additional_css_stylesheets: typeof relations_appearance_settings_additional_css_stylesheets;
  relations_appearance_settings: typeof relations_appearance_settings;
  relations_analytics_settings_additional_js_scripts: typeof relations_analytics_settings_additional_js_scripts;
  relations_analytics_settings: typeof relations_analytics_settings;
  relations_payload_jobs_stats: typeof relations_payload_jobs_stats;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
