/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    courses: Course;
    enrollments: Enrollment;
    origins: Origin;
    'activity-modules': ActivityModule;
    commits: Commit;
    tags: Tag;
    'course-activity-module-commit-links': CourseActivityModuleCommitLink;
    'merge-requests': MergeRequest;
    'merge-request-comments': MergeRequestComment;
    media: Media;
    notes: Note;
    gradebooks: Gradebook;
    'gradebook-categories': GradebookCategory;
    'gradebook-items': GradebookItem;
    'user-grades': UserGrade;
    search: Search;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    origins: {
      branches: 'activity-modules';
    };
    'activity-modules': {
      commits: 'commits';
    };
    'merge-requests': {
      comments: 'merge-request-comments';
    };
    gradebooks: {
      categories: 'gradebook-categories';
      items: 'gradebook-items';
    };
    'gradebook-categories': {
      subcategories: 'gradebook-categories';
      items: 'gradebook-items';
    };
    'gradebook-items': {
      userGrades: 'user-grades';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    origins: OriginsSelect<false> | OriginsSelect<true>;
    'activity-modules': ActivityModulesSelect<false> | ActivityModulesSelect<true>;
    commits: CommitsSelect<false> | CommitsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'course-activity-module-commit-links': CourseActivityModuleCommitLinksSelect<false> | CourseActivityModuleCommitLinksSelect<true>;
    'merge-requests': MergeRequestsSelect<false> | MergeRequestsSelect<true>;
    'merge-request-comments': MergeRequestCommentsSelect<false> | MergeRequestCommentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    gradebooks: GradebooksSelect<false> | GradebooksSelect<true>;
    'gradebook-categories': GradebookCategoriesSelect<false> | GradebookCategoriesSelect<true>;
    'gradebook-items': GradebookItemsSelect<false> | GradebookItemsSelect<true>;
    'user-grades': UserGradesSelect<false> | UserGradesSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role?: ('student' | 'instructor' | 'admin') | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug: string;
  description: string;
  structure: {
    sections: {
      title: string;
      description: string;
      lessons: {
        title: string;
        description: string;
      }[];
    }[];
  };
  status: 'draft' | 'published' | 'archived';
  thumbnail?: (number | null) | Media;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  user: number | User;
  userEmail?: string | null;
  course: number | Course;
  courseSlug?: string | null;
  courseTitle?: string | null;
  role: 'student' | 'teacher' | 'ta' | 'manager';
  status: 'active' | 'inactive' | 'completed' | 'dropped';
  enrolledAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "origins".
 */
export interface Origin {
  id: number;
  title: string;
  description?: string | null;
  branches?: {
    docs?: (number | ActivityModule)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-modules".
 */
export interface ActivityModule {
  id: number;
  branch: string;
  origin: number | Origin;
  title?: string | null;
  description?: string | null;
  commits?: {
    docs?: (number | Commit)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  type: 'page' | 'whiteboard' | 'assignment' | 'quiz' | 'discussion';
  status: 'draft' | 'published' | 'archived';
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commits".
 */
export interface Commit {
  id: number;
  hash: string;
  activityModule?: (number | ActivityModule)[] | null;
  message: string;
  author: number | User;
  parentCommit?: (number | null) | Commit;
  parentCommitHash?: string | null;
  commitDate: string;
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentHash: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  description?: string | null;
  commit: number | Commit;
  origin: number | Origin;
  tagType?: ('release' | 'milestone' | 'snapshot') | null;
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-activity-module-commit-links".
 */
export interface CourseActivityModuleCommitLink {
  id: number;
  course: number | Course;
  courseName?: string | null;
  courseSlug?: string | null;
  commit: number | Commit;
  activityModuleName?: string[] | null;
  activityModuleType?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merge-requests".
 */
export interface MergeRequest {
  id: number;
  title: string;
  description?: string | null;
  from: number | ActivityModule;
  to: number | ActivityModule;
  status: 'open' | 'merged' | 'rejected' | 'closed';
  comments?: {
    docs?: (number | MergeRequestComment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  rejectedAt?: string | null;
  rejectedBy?: (number | null) | User;
  mergedAt?: string | null;
  mergedBy?: (number | null) | User;
  createdBy: number | User;
  closedAt?: string | null;
  closedBy?: (number | null) | User;
  allowComments?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merge-request-comments".
 */
export interface MergeRequestComment {
  id: number;
  comment: string;
  createdBy: number | User;
  mergeRequest: number | MergeRequest;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  createdBy: number | User;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gradebooks".
 */
export interface Gradebook {
  id: number;
  course: number | Course;
  courseTitle?: string | null;
  enabled?: boolean | null;
  categories?: {
    docs?: (number | GradebookCategory)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  items?: {
    docs?: (number | GradebookItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gradebook-categories".
 */
export interface GradebookCategory {
  id: number;
  gradebook: number | Gradebook;
  parent?: (number | null) | GradebookCategory;
  name: string;
  description?: string | null;
  weight?: number | null;
  sortOrder: number;
  subcategories?: {
    docs?: (number | GradebookCategory)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  items?: {
    docs?: (number | GradebookItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gradebook-items".
 */
export interface GradebookItem {
  id: number;
  gradebook: number | Gradebook;
  category?: (number | null) | GradebookCategory;
  name: string;
  sortOrder: number;
  description?: string | null;
  activityModule?: (number | null) | CourseActivityModuleCommitLink;
  activityModuleName?: string[] | null;
  activityModuleType?: string[] | null;
  maxGrade: number;
  minGrade: number;
  weight: number;
  extraCredit?: boolean | null;
  userGrades?: {
    docs?: (number | UserGrade)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-grades".
 */
export interface UserGrade {
  id: number;
  enrollment: number | Enrollment;
  user?: string | null;
  userEmail?: string | null;
  course?: string | null;
  courseTitle?: string | null;
  gradebookItem: number | GradebookItem;
  grade?: number | null;
  feedback?: string | null;
  gradedBy?: (number | null) | User;
  gradedAt?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'courses';
        value: number | Course;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'origins';
        value: number | Origin;
      } | null)
    | ({
        relationTo: 'activity-modules';
        value: number | ActivityModule;
      } | null)
    | ({
        relationTo: 'commits';
        value: number | Commit;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'course-activity-module-commit-links';
        value: number | CourseActivityModuleCommitLink;
      } | null)
    | ({
        relationTo: 'merge-requests';
        value: number | MergeRequest;
      } | null)
    | ({
        relationTo: 'merge-request-comments';
        value: number | MergeRequestComment;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'gradebooks';
        value: number | Gradebook;
      } | null)
    | ({
        relationTo: 'gradebook-categories';
        value: number | GradebookCategory;
      } | null)
    | ({
        relationTo: 'gradebook-items';
        value: number | GradebookItem;
      } | null)
    | ({
        relationTo: 'user-grades';
        value: number | UserGrade;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  structure?: T;
  status?: T;
  thumbnail?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  user?: T;
  userEmail?: T;
  course?: T;
  courseSlug?: T;
  courseTitle?: T;
  role?: T;
  status?: T;
  enrolledAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "origins_select".
 */
export interface OriginsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  branches?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-modules_select".
 */
export interface ActivityModulesSelect<T extends boolean = true> {
  branch?: T;
  origin?: T;
  title?: T;
  description?: T;
  commits?: T;
  type?: T;
  status?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commits_select".
 */
export interface CommitsSelect<T extends boolean = true> {
  hash?: T;
  activityModule?: T;
  message?: T;
  author?: T;
  parentCommit?: T;
  parentCommitHash?: T;
  commitDate?: T;
  content?: T;
  contentHash?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  commit?: T;
  origin?: T;
  tagType?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-activity-module-commit-links_select".
 */
export interface CourseActivityModuleCommitLinksSelect<T extends boolean = true> {
  course?: T;
  courseName?: T;
  courseSlug?: T;
  commit?: T;
  activityModuleName?: T;
  activityModuleType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merge-requests_select".
 */
export interface MergeRequestsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  from?: T;
  to?: T;
  status?: T;
  comments?: T;
  rejectedAt?: T;
  rejectedBy?: T;
  mergedAt?: T;
  mergedBy?: T;
  createdBy?: T;
  closedAt?: T;
  closedBy?: T;
  allowComments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merge-request-comments_select".
 */
export interface MergeRequestCommentsSelect<T extends boolean = true> {
  comment?: T;
  createdBy?: T;
  mergeRequest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  createdBy?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gradebooks_select".
 */
export interface GradebooksSelect<T extends boolean = true> {
  course?: T;
  courseTitle?: T;
  enabled?: T;
  categories?: T;
  items?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gradebook-categories_select".
 */
export interface GradebookCategoriesSelect<T extends boolean = true> {
  gradebook?: T;
  parent?: T;
  name?: T;
  description?: T;
  weight?: T;
  sortOrder?: T;
  subcategories?: T;
  items?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gradebook-items_select".
 */
export interface GradebookItemsSelect<T extends boolean = true> {
  gradebook?: T;
  category?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  activityModule?: T;
  activityModuleName?: T;
  activityModuleType?: T;
  maxGrade?: T;
  minGrade?: T;
  weight?: T;
  extraCredit?: T;
  userGrades?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-grades_select".
 */
export interface UserGradesSelect<T extends boolean = true> {
  enrollment?: T;
  user?: T;
  userEmail?: T;
  course?: T;
  courseTitle?: T;
  gradebookItem?: T;
  grade?: T;
  feedback?: T;
  gradedBy?: T;
  gradedAt?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}