/**
 * Re-export all errors and transformError from the backend package.
 * The backend is the source of truth for error definitions.
 */
export {
	ContextNotFoundError,
	UnauthorizedError,
	DuplicateActivityModuleError,
	InvalidArgumentError,
	TransactionIdNotFoundError,
	NonExistingActivityModuleError,
	UnknownError,
	EnrollmentNotFoundError,
	DuplicateEnrollmentError,
	NonExistingMediaError,
	DevelopmentError,
	GradebookNotFoundError,
	GradebookCategoryNotFoundError,
	GradebookItemNotFoundError,
	UserGradeNotFoundError,
	DuplicateGradebookError,
	InvalidGradeValueError,
	InvalidSortOrderError,
	WeightExceedsLimitError,
	WeightZeroRequiredError,
	NonExistingAssignmentSubmissionError,
	NonExistingQuizSubmissionError,
	NonExistingDiscussionSubmissionError,
	ActivityModuleAccessDeniedError,
	DuplicateAccessGrantError,
	AccessGrantNotFoundError,
	InvalidOwnerTransferError,
	CourseAccessDeniedError,
	EmailSendError,
	SeedDataLoadError,
	SandboxResetError,
	MediaInUseError,
	S3BucketNotFoundError,
	QuizTimeLimitExceededError,
	DuplicateUserGradeError,
	UserNotFoundError,
	EnrollmentCourseMismatchError,
	NotImplementedError,
	ValidationError,
	QuizConfigValidationError,
	QuizElementNotFoundError,
	transformError,
} from "@paideia/core";
