/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  boolean,
  numeric,
  type AnyPgColumn,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_role = pgEnum("enum_users_role", [
  "student",
  "instructor",
  "admin",
]);
export const enum_courses_difficulty = pgEnum("enum_courses_difficulty", [
  "beginner",
  "intermediate",
  "advanced",
]);
export const enum_courses_status = pgEnum("enum_courses_status", [
  "draft",
  "published",
  "archived",
]);
export const enum_enrollments_role = pgEnum("enum_enrollments_role", [
  "student",
  "teacher",
  "ta",
  "manager",
]);
export const enum_enrollments_status = pgEnum("enum_enrollments_status", [
  "active",
  "inactive",
  "completed",
  "dropped",
]);
export const enum_activity_modules_type = pgEnum("enum_activity_modules_type", [
  "page",
  "whiteboard",
  "assignment",
  "quiz",
  "discussion",
]);
export const enum_activity_modules_status = pgEnum(
  "enum_activity_modules_status",
  ["draft", "published", "archived"],
);
export const enum_tags_tag_type = pgEnum("enum_tags_tag_type", [
  "release",
  "milestone",
  "snapshot",
]);
export const enum_merge_requests_status = pgEnum("enum_merge_requests_status", [
  "open",
  "merged",
  "rejected",
  "closed",
]);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => ({
    _orderIdx: index("users_sessions_order_idx").on(columns._order),
    _parentIDIdx: index("users_sessions_parent_id_idx").on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    firstName: varchar("first_name"),
    lastName: varchar("last_name"),
    role: enum_users_role("role").default("student"),
    bio: varchar("bio"),
    avatar: integer("avatar_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    _verified: boolean("_verified"),
    _verificationToken: varchar("_verificationtoken"),
    loginAttempts: numeric("login_attempts").default("0"),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    users_avatar_idx: index("users_avatar_idx").on(columns.avatar),
    users_updated_at_idx: index("users_updated_at_idx").on(columns.updatedAt),
    users_created_at_idx: index("users_created_at_idx").on(columns.createdAt),
    users_email_idx: uniqueIndex("users_email_idx").on(columns.email),
  }),
);

export const courses_tags = pgTable(
  "courses_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    tag: varchar("tag"),
  },
  (columns) => ({
    _orderIdx: index("courses_tags_order_idx").on(columns._order),
    _parentIDIdx: index("courses_tags_parent_id_idx").on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [courses.id],
      name: "courses_tags_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const courses = pgTable(
  "courses",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description").notNull(),
    instructor: integer("instructor_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    difficulty: enum_courses_difficulty("difficulty").default("beginner"),
    duration: numeric("duration"),
    status: enum_courses_status("status").default("draft"),
    thumbnail: integer("thumbnail_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    courses_instructor_idx: index("courses_instructor_idx").on(
      columns.instructor,
    ),
    courses_thumbnail_idx: index("courses_thumbnail_idx").on(columns.thumbnail),
    courses_updated_at_idx: index("courses_updated_at_idx").on(
      columns.updatedAt,
    ),
    courses_created_at_idx: index("courses_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const enrollments = pgTable(
  "enrollments",
  {
    id: serial("id").primaryKey(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    course: integer("course_id")
      .notNull()
      .references(() => courses.id, {
        onDelete: "set null",
      }),
    role: enum_enrollments_role("role").notNull(),
    status: enum_enrollments_status("status").default("active"),
    enrolledAt: timestamp("enrolled_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    enrollments_user_idx: index("enrollments_user_idx").on(columns.user),
    enrollments_course_idx: index("enrollments_course_idx").on(columns.course),
    enrollments_updated_at_idx: index("enrollments_updated_at_idx").on(
      columns.updatedAt,
    ),
    enrollments_created_at_idx: index("enrollments_created_at_idx").on(
      columns.createdAt,
    ),
    user_course_idx: uniqueIndex("user_course_idx").on(
      columns.user,
      columns.course,
    ),
  }),
);

export const origins = pgTable(
  "origins",
  {
    id: serial("id").primaryKey(),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    origins_created_by_idx: index("origins_created_by_idx").on(
      columns.createdBy,
    ),
    origins_updated_at_idx: index("origins_updated_at_idx").on(
      columns.updatedAt,
    ),
    origins_created_at_idx: index("origins_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const activity_modules = pgTable(
  "activity_modules",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description"),
    branch: varchar("branch").notNull().default("main"),
    origin: integer("origin_id")
      .notNull()
      .references(() => origins.id, {
        onDelete: "set null",
      }),
    type: enum_activity_modules_type("type").notNull(),
    status: enum_activity_modules_status("status").default("draft"),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    activity_modules_origin_idx: index("activity_modules_origin_idx").on(
      columns.origin,
    ),
    activity_modules_created_by_idx: index(
      "activity_modules_created_by_idx",
    ).on(columns.createdBy),
    activity_modules_updated_at_idx: index(
      "activity_modules_updated_at_idx",
    ).on(columns.updatedAt),
    activity_modules_created_at_idx: index(
      "activity_modules_created_at_idx",
    ).on(columns.createdAt),
    branch_origin_idx: uniqueIndex("branch_origin_idx").on(
      columns.branch,
      columns.origin,
    ),
  }),
);

export const commits = pgTable(
  "commits",
  {
    id: serial("id").primaryKey(),
    hash: varchar("hash").notNull(),
    message: varchar("message").notNull(),
    author: integer("author_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    parentCommit: integer("parent_commit_id").references(
      (): AnyPgColumn => commits.id,
      {
        onDelete: "set null",
      },
    ),
    commitDate: timestamp("commit_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    content: jsonb("content").notNull(),
    contentHash: varchar("content_hash").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    commits_hash_idx: uniqueIndex("commits_hash_idx").on(columns.hash),
    commits_author_idx: index("commits_author_idx").on(columns.author),
    commits_parent_commit_idx: index("commits_parent_commit_idx").on(
      columns.parentCommit,
    ),
    commits_updated_at_idx: index("commits_updated_at_idx").on(
      columns.updatedAt,
    ),
    commits_created_at_idx: index("commits_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const commits_rels = pgTable(
  "commits_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "activity-modulesID": integer("activity_modules_id"),
  },
  (columns) => ({
    order: index("commits_rels_order_idx").on(columns.order),
    parentIdx: index("commits_rels_parent_idx").on(columns.parent),
    pathIdx: index("commits_rels_path_idx").on(columns.path),
    commits_rels_activity_modules_id_idx: index(
      "commits_rels_activity_modules_id_idx",
    ).on(columns["activity-modulesID"]),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [commits.id],
      name: "commits_rels_parent_fk",
    }).onDelete("cascade"),
    "activity-modulesIdFk": foreignKey({
      columns: [columns["activity-modulesID"]],
      foreignColumns: [activity_modules.id],
      name: "commits_rels_activity_modules_fk",
    }).onDelete("cascade"),
  }),
);

export const tags = pgTable(
  "tags",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    description: varchar("description"),
    commit: integer("commit_id")
      .notNull()
      .references(() => commits.id, {
        onDelete: "set null",
      }),
    origin: integer("origin_id")
      .notNull()
      .references(() => origins.id, {
        onDelete: "set null",
      }),
    tagType: enum_tags_tag_type("tag_type").default("snapshot"),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    tags_name_idx: uniqueIndex("tags_name_idx").on(columns.name),
    tags_commit_idx: index("tags_commit_idx").on(columns.commit),
    tags_origin_idx: index("tags_origin_idx").on(columns.origin),
    tags_created_by_idx: index("tags_created_by_idx").on(columns.createdBy),
    tags_updated_at_idx: index("tags_updated_at_idx").on(columns.updatedAt),
    tags_created_at_idx: index("tags_created_at_idx").on(columns.createdAt),
    name_origin_idx: uniqueIndex("name_origin_idx").on(
      columns.name,
      columns.origin,
    ),
  }),
);

export const merge_requests = pgTable(
  "merge_requests",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description"),
    from: integer("from_id")
      .notNull()
      .references(() => activity_modules.id, {
        onDelete: "set null",
      }),
    to: integer("to_id")
      .notNull()
      .references(() => activity_modules.id, {
        onDelete: "set null",
      }),
    status: enum_merge_requests_status("status").default("open"),
    rejectedAt: timestamp("rejected_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    rejectedBy: integer("rejected_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    mergedAt: timestamp("merged_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    mergedBy: integer("merged_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    merge_requests_from_idx: index("merge_requests_from_idx").on(columns.from),
    merge_requests_to_idx: index("merge_requests_to_idx").on(columns.to),
    merge_requests_rejected_by_idx: index("merge_requests_rejected_by_idx").on(
      columns.rejectedBy,
    ),
    merge_requests_merged_by_idx: index("merge_requests_merged_by_idx").on(
      columns.mergedBy,
    ),
    merge_requests_created_by_idx: index("merge_requests_created_by_idx").on(
      columns.createdBy,
    ),
    merge_requests_updated_at_idx: index("merge_requests_updated_at_idx").on(
      columns.updatedAt,
    ),
    merge_requests_created_at_idx: index("merge_requests_created_at_idx").on(
      columns.createdAt,
    ),
    from_to_idx: uniqueIndex("from_to_idx").on(columns.from, columns.to),
  }),
);

export const merge_request_comments = pgTable(
  "merge_request_comments",
  {
    id: serial("id").primaryKey(),
    comment: varchar("comment").notNull(),
    createdBy: integer("created_by_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    mergeRequest: integer("merge_request_id")
      .notNull()
      .references(() => merge_requests.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    merge_request_comments_created_by_idx: index(
      "merge_request_comments_created_by_idx",
    ).on(columns.createdBy),
    merge_request_comments_merge_request_idx: index(
      "merge_request_comments_merge_request_idx",
    ).on(columns.mergeRequest),
    merge_request_comments_updated_at_idx: index(
      "merge_request_comments_updated_at_idx",
    ).on(columns.updatedAt),
    merge_request_comments_created_at_idx: index(
      "merge_request_comments_created_at_idx",
    ).on(columns.createdAt),
    mergeRequest_idx: uniqueIndex("mergeRequest_idx").on(columns.mergeRequest),
  }),
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt"),
    caption: varchar("caption"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize"),
    width: numeric("width"),
    height: numeric("height"),
    focalX: numeric("focal_x"),
    focalY: numeric("focal_y"),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width"),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height"),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize"),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width"),
    sizes_card_height: numeric("sizes_card_height"),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize"),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_tablet_url: varchar("sizes_tablet_url"),
    sizes_tablet_width: numeric("sizes_tablet_width"),
    sizes_tablet_height: numeric("sizes_tablet_height"),
    sizes_tablet_mimeType: varchar("sizes_tablet_mime_type"),
    sizes_tablet_filesize: numeric("sizes_tablet_filesize"),
    sizes_tablet_filename: varchar("sizes_tablet_filename"),
  },
  (columns) => ({
    media_updated_at_idx: index("media_updated_at_idx").on(columns.updatedAt),
    media_created_at_idx: index("media_created_at_idx").on(columns.createdAt),
    media_filename_idx: uniqueIndex("media_filename_idx").on(columns.filename),
    media_sizes_thumbnail_sizes_thumbnail_filename_idx: index(
      "media_sizes_thumbnail_sizes_thumbnail_filename_idx",
    ).on(columns.sizes_thumbnail_filename),
    media_sizes_card_sizes_card_filename_idx: index(
      "media_sizes_card_sizes_card_filename_idx",
    ).on(columns.sizes_card_filename),
    media_sizes_tablet_sizes_tablet_filename_idx: index(
      "media_sizes_tablet_sizes_tablet_filename_idx",
    ).on(columns.sizes_tablet_filename),
  }),
);

export const search = pgTable(
  "search",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    priority: numeric("priority"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    search_updated_at_idx: index("search_updated_at_idx").on(columns.updatedAt),
    search_created_at_idx: index("search_created_at_idx").on(columns.createdAt),
  }),
);

export const search_rels = pgTable(
  "search_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    coursesID: integer("courses_id"),
  },
  (columns) => ({
    order: index("search_rels_order_idx").on(columns.order),
    parentIdx: index("search_rels_parent_idx").on(columns.parent),
    pathIdx: index("search_rels_path_idx").on(columns.path),
    search_rels_users_id_idx: index("search_rels_users_id_idx").on(
      columns.usersID,
    ),
    search_rels_courses_id_idx: index("search_rels_courses_id_idx").on(
      columns.coursesID,
    ),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [search.id],
      name: "search_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "search_rels_users_fk",
    }).onDelete("cascade"),
    coursesIdFk: foreignKey({
      columns: [columns["coursesID"]],
      foreignColumns: [courses.id],
      name: "search_rels_courses_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index(
      "payload_locked_documents_global_slug_idx",
    ).on(columns.globalSlug),
    payload_locked_documents_updated_at_idx: index(
      "payload_locked_documents_updated_at_idx",
    ).on(columns.updatedAt),
    payload_locked_documents_created_at_idx: index(
      "payload_locked_documents_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    coursesID: integer("courses_id"),
    enrollmentsID: integer("enrollments_id"),
    originsID: integer("origins_id"),
    "activity-modulesID": integer("activity_modules_id"),
    commitsID: integer("commits_id"),
    tagsID: integer("tags_id"),
    "merge-requestsID": integer("merge_requests_id"),
    "merge-request-commentsID": integer("merge_request_comments_id"),
    mediaID: integer("media_id"),
    searchID: integer("search_id"),
  },
  (columns) => ({
    order: index("payload_locked_documents_rels_order_idx").on(columns.order),
    parentIdx: index("payload_locked_documents_rels_parent_idx").on(
      columns.parent,
    ),
    pathIdx: index("payload_locked_documents_rels_path_idx").on(columns.path),
    payload_locked_documents_rels_users_id_idx: index(
      "payload_locked_documents_rels_users_id_idx",
    ).on(columns.usersID),
    payload_locked_documents_rels_courses_id_idx: index(
      "payload_locked_documents_rels_courses_id_idx",
    ).on(columns.coursesID),
    payload_locked_documents_rels_enrollments_id_idx: index(
      "payload_locked_documents_rels_enrollments_id_idx",
    ).on(columns.enrollmentsID),
    payload_locked_documents_rels_origins_id_idx: index(
      "payload_locked_documents_rels_origins_id_idx",
    ).on(columns.originsID),
    payload_locked_documents_rels_activity_modules_id_idx: index(
      "payload_locked_documents_rels_activity_modules_id_idx",
    ).on(columns["activity-modulesID"]),
    payload_locked_documents_rels_commits_id_idx: index(
      "payload_locked_documents_rels_commits_id_idx",
    ).on(columns.commitsID),
    payload_locked_documents_rels_tags_id_idx: index(
      "payload_locked_documents_rels_tags_id_idx",
    ).on(columns.tagsID),
    payload_locked_documents_rels_merge_requests_id_idx: index(
      "payload_locked_documents_rels_merge_requests_id_idx",
    ).on(columns["merge-requestsID"]),
    payload_locked_documents_rels_merge_request_comments_id_idx: index(
      "payload_locked_documents_rels_merge_request_comments_id_idx",
    ).on(columns["merge-request-commentsID"]),
    payload_locked_documents_rels_media_id_idx: index(
      "payload_locked_documents_rels_media_id_idx",
    ).on(columns.mediaID),
    payload_locked_documents_rels_search_id_idx: index(
      "payload_locked_documents_rels_search_id_idx",
    ).on(columns.searchID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    coursesIdFk: foreignKey({
      columns: [columns["coursesID"]],
      foreignColumns: [courses.id],
      name: "payload_locked_documents_rels_courses_fk",
    }).onDelete("cascade"),
    enrollmentsIdFk: foreignKey({
      columns: [columns["enrollmentsID"]],
      foreignColumns: [enrollments.id],
      name: "payload_locked_documents_rels_enrollments_fk",
    }).onDelete("cascade"),
    originsIdFk: foreignKey({
      columns: [columns["originsID"]],
      foreignColumns: [origins.id],
      name: "payload_locked_documents_rels_origins_fk",
    }).onDelete("cascade"),
    "activity-modulesIdFk": foreignKey({
      columns: [columns["activity-modulesID"]],
      foreignColumns: [activity_modules.id],
      name: "payload_locked_documents_rels_activity_modules_fk",
    }).onDelete("cascade"),
    commitsIdFk: foreignKey({
      columns: [columns["commitsID"]],
      foreignColumns: [commits.id],
      name: "payload_locked_documents_rels_commits_fk",
    }).onDelete("cascade"),
    tagsIdFk: foreignKey({
      columns: [columns["tagsID"]],
      foreignColumns: [tags.id],
      name: "payload_locked_documents_rels_tags_fk",
    }).onDelete("cascade"),
    "merge-requestsIdFk": foreignKey({
      columns: [columns["merge-requestsID"]],
      foreignColumns: [merge_requests.id],
      name: "payload_locked_documents_rels_merge_requests_fk",
    }).onDelete("cascade"),
    "merge-request-commentsIdFk": foreignKey({
      columns: [columns["merge-request-commentsID"]],
      foreignColumns: [merge_request_comments.id],
      name: "payload_locked_documents_rels_merge_request_comments_fk",
    }).onDelete("cascade"),
    mediaIdFk: foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    searchIdFk: foreignKey({
      columns: [columns["searchID"]],
      foreignColumns: [search.id],
      name: "payload_locked_documents_rels_search_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index("payload_preferences_key_idx").on(
      columns.key,
    ),
    payload_preferences_updated_at_idx: index(
      "payload_preferences_updated_at_idx",
    ).on(columns.updatedAt),
    payload_preferences_created_at_idx: index(
      "payload_preferences_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => ({
    order: index("payload_preferences_rels_order_idx").on(columns.order),
    parentIdx: index("payload_preferences_rels_parent_idx").on(columns.parent),
    pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
    payload_preferences_rels_users_id_idx: index(
      "payload_preferences_rels_users_id_idx",
    ).on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index(
      "payload_migrations_updated_at_idx",
    ).on(columns.updatedAt),
    payload_migrations_created_at_idx: index(
      "payload_migrations_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_courses_tags = relations(courses_tags, ({ one }) => ({
  _parentID: one(courses, {
    fields: [courses_tags._parentID],
    references: [courses.id],
    relationName: "tags",
  }),
}));
export const relations_courses = relations(courses, ({ one, many }) => ({
  instructor: one(users, {
    fields: [courses.instructor],
    references: [users.id],
    relationName: "instructor",
  }),
  thumbnail: one(media, {
    fields: [courses.thumbnail],
    references: [media.id],
    relationName: "thumbnail",
  }),
  tags: many(courses_tags, {
    relationName: "tags",
  }),
}));
export const relations_enrollments = relations(enrollments, ({ one }) => ({
  user: one(users, {
    fields: [enrollments.user],
    references: [users.id],
    relationName: "user",
  }),
  course: one(courses, {
    fields: [enrollments.course],
    references: [courses.id],
    relationName: "course",
  }),
}));
export const relations_origins = relations(origins, ({ one }) => ({
  createdBy: one(users, {
    fields: [origins.createdBy],
    references: [users.id],
    relationName: "createdBy",
  }),
}));
export const relations_activity_modules = relations(
  activity_modules,
  ({ one }) => ({
    origin: one(origins, {
      fields: [activity_modules.origin],
      references: [origins.id],
      relationName: "origin",
    }),
    createdBy: one(users, {
      fields: [activity_modules.createdBy],
      references: [users.id],
      relationName: "createdBy",
    }),
  }),
);
export const relations_commits_rels = relations(commits_rels, ({ one }) => ({
  parent: one(commits, {
    fields: [commits_rels.parent],
    references: [commits.id],
    relationName: "_rels",
  }),
  "activity-modulesID": one(activity_modules, {
    fields: [commits_rels["activity-modulesID"]],
    references: [activity_modules.id],
    relationName: "activity-modules",
  }),
}));
export const relations_commits = relations(commits, ({ one, many }) => ({
  author: one(users, {
    fields: [commits.author],
    references: [users.id],
    relationName: "author",
  }),
  parentCommit: one(commits, {
    fields: [commits.parentCommit],
    references: [commits.id],
    relationName: "parentCommit",
  }),
  _rels: many(commits_rels, {
    relationName: "_rels",
  }),
}));
export const relations_tags = relations(tags, ({ one }) => ({
  commit: one(commits, {
    fields: [tags.commit],
    references: [commits.id],
    relationName: "commit",
  }),
  origin: one(origins, {
    fields: [tags.origin],
    references: [origins.id],
    relationName: "origin",
  }),
  createdBy: one(users, {
    fields: [tags.createdBy],
    references: [users.id],
    relationName: "createdBy",
  }),
}));
export const relations_merge_requests = relations(
  merge_requests,
  ({ one }) => ({
    from: one(activity_modules, {
      fields: [merge_requests.from],
      references: [activity_modules.id],
      relationName: "from",
    }),
    to: one(activity_modules, {
      fields: [merge_requests.to],
      references: [activity_modules.id],
      relationName: "to",
    }),
    rejectedBy: one(users, {
      fields: [merge_requests.rejectedBy],
      references: [users.id],
      relationName: "rejectedBy",
    }),
    mergedBy: one(users, {
      fields: [merge_requests.mergedBy],
      references: [users.id],
      relationName: "mergedBy",
    }),
    createdBy: one(users, {
      fields: [merge_requests.createdBy],
      references: [users.id],
      relationName: "createdBy",
    }),
  }),
);
export const relations_merge_request_comments = relations(
  merge_request_comments,
  ({ one }) => ({
    createdBy: one(users, {
      fields: [merge_request_comments.createdBy],
      references: [users.id],
      relationName: "createdBy",
    }),
    mergeRequest: one(merge_requests, {
      fields: [merge_request_comments.mergeRequest],
      references: [merge_requests.id],
      relationName: "mergeRequest",
    }),
  }),
);
export const relations_media = relations(media, () => ({}));
export const relations_search_rels = relations(search_rels, ({ one }) => ({
  parent: one(search, {
    fields: [search_rels.parent],
    references: [search.id],
    relationName: "_rels",
  }),
  usersID: one(users, {
    fields: [search_rels.usersID],
    references: [users.id],
    relationName: "users",
  }),
  coursesID: one(courses, {
    fields: [search_rels.coursesID],
    references: [courses.id],
    relationName: "courses",
  }),
}));
export const relations_search = relations(search, ({ many }) => ({
  _rels: many(search_rels, {
    relationName: "_rels",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    coursesID: one(courses, {
      fields: [payload_locked_documents_rels.coursesID],
      references: [courses.id],
      relationName: "courses",
    }),
    enrollmentsID: one(enrollments, {
      fields: [payload_locked_documents_rels.enrollmentsID],
      references: [enrollments.id],
      relationName: "enrollments",
    }),
    originsID: one(origins, {
      fields: [payload_locked_documents_rels.originsID],
      references: [origins.id],
      relationName: "origins",
    }),
    "activity-modulesID": one(activity_modules, {
      fields: [payload_locked_documents_rels["activity-modulesID"]],
      references: [activity_modules.id],
      relationName: "activity-modules",
    }),
    commitsID: one(commits, {
      fields: [payload_locked_documents_rels.commitsID],
      references: [commits.id],
      relationName: "commits",
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: "tags",
    }),
    "merge-requestsID": one(merge_requests, {
      fields: [payload_locked_documents_rels["merge-requestsID"]],
      references: [merge_requests.id],
      relationName: "merge-requests",
    }),
    "merge-request-commentsID": one(merge_request_comments, {
      fields: [payload_locked_documents_rels["merge-request-commentsID"]],
      references: [merge_request_comments.id],
      relationName: "merge-request-comments",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    searchID: one(search, {
      fields: [payload_locked_documents_rels.searchID],
      references: [search.id],
      relationName: "search",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role;
  enum_courses_difficulty: typeof enum_courses_difficulty;
  enum_courses_status: typeof enum_courses_status;
  enum_enrollments_role: typeof enum_enrollments_role;
  enum_enrollments_status: typeof enum_enrollments_status;
  enum_activity_modules_type: typeof enum_activity_modules_type;
  enum_activity_modules_status: typeof enum_activity_modules_status;
  enum_tags_tag_type: typeof enum_tags_tag_type;
  enum_merge_requests_status: typeof enum_merge_requests_status;
  users_sessions: typeof users_sessions;
  users: typeof users;
  courses_tags: typeof courses_tags;
  courses: typeof courses;
  enrollments: typeof enrollments;
  origins: typeof origins;
  activity_modules: typeof activity_modules;
  commits: typeof commits;
  commits_rels: typeof commits_rels;
  tags: typeof tags;
  merge_requests: typeof merge_requests;
  merge_request_comments: typeof merge_request_comments;
  media: typeof media;
  search: typeof search;
  search_rels: typeof search_rels;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_courses_tags: typeof relations_courses_tags;
  relations_courses: typeof relations_courses;
  relations_enrollments: typeof relations_enrollments;
  relations_origins: typeof relations_origins;
  relations_activity_modules: typeof relations_activity_modules;
  relations_commits_rels: typeof relations_commits_rels;
  relations_commits: typeof relations_commits;
  relations_tags: typeof relations_tags;
  relations_merge_requests: typeof relations_merge_requests;
  relations_merge_request_comments: typeof relations_merge_request_comments;
  relations_media: typeof relations_media;
  relations_search_rels: typeof relations_search_rels;
  relations_search: typeof relations_search;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
